"""Budget entry points and a session-protected rate settings page."""


def calculator(g, compact=False):
    eyebrow = 'Бюджет / первый ориентир' if compact else 'Параметры вашего объекта'
    title = 'Оценить бюджет<br>вашего проекта.' if compact else 'Несколько параметров.<br>Первый ориентир.'
    body = '''<section class="section budget-section%s" id="budget"><div class="budget-heading"><div><p class="eyebrow">%s</p><h2>%s</h2></div><p>Выберите состав работ, объём и условия объекта. Точное предложение подготовим после изучения проекта.</p></div><div class="budget-layout"><form class="budget-form" data-budget-form><div class="budget-fields"><label class="budget-wide">Направление<select name="service" required><option value="glazing">Фасадное остекление</option><option value="windows">Оконные системы</option><option value="repair">Ремонт и восстановление</option></select></label><fieldset class="budget-scope budget-wide"><legend>Состав работ</legend><label><input type="radio" name="scope" value="installation" checked><span>Только монтаж</span></label><label><input type="radio" name="scope" value="supply-installation"><span>Поставка и монтаж</span></label></fieldset><label>Объём, м²<input name="area" type="number" min="1" max="1000000" step="any" inputmode="decimal" placeholder="Площадь работ" required></label><label>Регион<select name="region" required><option value="">Загружаем регионы…</option></select></label><label class="budget-wide">Высота работ<select name="height" required><option value="">Загружаем условия…</option></select></label></div><button class="button budget-submit" type="submit">Подготовить запрос КП ↗</button><p class="budget-message" role="status" aria-live="polite"></p><noscript><p>Для калькулятора включите JavaScript или <a href="quote.html">запросите КП у менеджера</a>.</p></noscript></form><aside class="budget-result" aria-label="Предварительный бюджет"><p class="eyebrow">Предварительный расчёт</p><h3 data-budget-title>Оставьте объём — менеджер подготовит расчёт</h3><p class="budget-value" data-budget-value hidden></p><p data-budget-note>Параметры объекта перенесём в запрос КП.</p><dl class="budget-summary" data-budget-summary hidden></dl><a class="button button-light" data-budget-quote href="quote.html">Запросить точное КП ↗</a><a class="text-button" href="%s">%s ↗</a></aside></div></section>'''
    body = body.replace('<a class="text-button" href="%s">', '<div class="budget-share"><button class="text-button" type="button" data-budget-share disabled>Поделиться параметрами</button><div class="budget-share-output" data-budget-share-output hidden><input type="url" readonly data-budget-share-link aria-label="Ссылка с параметрами объекта"><p data-budget-share-status role="status" aria-live="polite"></p></div></div><a class="text-button" href="%s">', 1)
    return body % (' budget-compact' if compact else '', eyebrow, title, 'budget.html' if compact else 'services.html', 'Открыть калькулятор' if compact else 'Посмотреть состав услуг')


def enhance(g, path, body):
    if path == 'index.html':
        anchor = '<section class="section faq-section">'
        widget = calculator(g, compact=True)
        body = body.replace(anchor, widget + anchor, 1) if anchor in body else body + widget
    return body


def pages(g):
    g['page']('budget.html', 'Предварительный расчёт бюджета', 'Предварительный бюджет фасадного остекления, оконных систем и ремонта: состав работ, объём, регион и высота.', g['intro']('Стоимость / ваш объект', 'Начните с объёма<br>и состава работ.', 'Выберите условия объекта и передайте исходные данные для коммерческого предложения.') + calculator(g), 'services')
    admin = g['OUT'] / 'admin' / 'budget.html'
    admin.parent.mkdir(parents=True, exist_ok=True)
    admin.write_text('''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Прайс калькулятора — ФАСАД.PRO</title><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/enhancements.css"><link rel="stylesheet" href="/admin/admin.css"><link rel="stylesheet" href="/admin/budget14.css"><script src="/admin/budget14.js" defer></script></head><body class="budget-admin"><header class="budget-admin-header"><a href="/admin/" aria-label="К заявкам"><img src="/assets/logo.svg" alt="ФАСАД.PRO" width="160" height="44"></a><a class="text-button" href="/admin/">← К заявкам</a></header><main class="budget-admin-main"><div class="budget-admin-title"><div><p class="muted">Настройки / предварительный бюджет</p><h1>Прайс калькулятора</h1><p>Укажите согласованные диапазоны стоимости за м². Пустой прайс направляет заказчика к менеджеру.</p></div><a class="button button-outline" href="/budget.html" target="_blank" rel="noopener">Открыть калькулятор ↗</a></div><div id="budget-auth" class="admin-panel" hidden><h2>Войдите в панель менеджера</h2><p>Настройки прайса доступны после входа.</p><a class="button" href="/admin/">Войти ↗</a></div><p id="budget-admin-status" role="status" aria-live="polite">Загружаем настройки…</p><form id="budget-settings" hidden><section class="admin-panel"><div class="budget-section-title"><div><h2>Стоимость работ</h2><p class="muted">Диапазон за м² до применения коэффициентов региона и высоты.</p></div><button type="button" class="button button-outline" data-add="rate">Добавить ставку +</button></div><div id="budget-rates" class="budget-setting-list"></div><p id="budget-empty" class="budget-empty">Ставок пока нет. На сайте заказчик сможет передать параметры менеджеру.</p></section><div class="budget-factor-grid"><section class="admin-panel"><div class="budget-section-title"><h2>Регионы</h2><button type="button" class="text-button" data-add="region">Добавить +</button></div><p class="muted">Коэффициент применяется к выбранной ставке.</p><div id="budget-regions" class="budget-setting-list"></div></section><section class="admin-panel"><div class="budget-section-title"><h2>Высота работ</h2><button type="button" class="text-button" data-add="height">Добавить +</button></div><p class="muted">Коэффициент применяется после выбора региона.</p><div id="budget-heights" class="budget-setting-list"></div></section></div><div class="budget-save-bar"><div><button class="button" id="budget-save" type="submit">Сохранить прайс</button><button class="text-button" id="budget-reload" type="button">Загрузить сохранённый</button></div><p id="budget-revision" class="muted"></p></div><p id="budget-save-status" role="status" aria-live="polite"></p></form></main></body></html>''', encoding='utf-8')
