"""Public pages for release 4. Data is embedded inertly and escaped once."""
import json,html,re

def data_element(value):
 return '<script type="application/json" id="release-data">'+json.dumps(value,ensure_ascii=False).replace('<','\\u003c')+'</script>'

def hero(g):
 projects=g['P'];by={p['id']:p for p in projects};chosen=[by[k] for k in ['museum','restaurant','burny'] if k in by]
 chosen=(chosen+[p for p in projects if p not in chosen])[:3]
 e=g['e'];button=g['button'];arrow=g['ARROW']
 slides=''.join(f'<div class="showcase-slide" id="showcase-{i}" role="tabpanel" aria-labelledby="showcase-tab-{i}" {"hidden" if i else ""}>{g["img"]((p["images"] or [None])[0],p["title"],eager=i==0)}<a class="showcase-caption" href="projects/{p["id"]}.html"><span><small>{p["type"]}</small><strong>{p["title"]}</strong><span>{p["period"] if p["volume"].lower() in p["period"].lower() else p["volume"]+" · "+p["period"]}</span></span>{arrow}</a></div>' for i,p in enumerate(chosen))
 tabs=''.join(f'<button type="button" role="tab" id="showcase-tab-{i}" aria-controls="showcase-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}" data-slide="{i}"><span>0{i+1}</span><strong>{p["title"]}</strong></button>' for i,p in enumerate(chosen))
 slogan=e(g['CFG']['slogan']).replace(' любой ','<br>любой<br>')
 return f'''<section class="showcase" aria-label="Ключевые проекты"><div class="showcase-copy"><p class="eyebrow">Остекление · Монтаж · Восстановление</p><h1>{slogan}</h1><p class="showcase-intro">От точного узла<br>до выразительной архитектуры.</p><div class="showcase-actions">{button('Обсудить проект','request.html',True)}<a href="solutions.html" class="text-button">Подобрать решение {arrow}</a></div><a class="showcase-download portfolio-download" href="downloads/portfolio.pdf" download>Портфолио компании / PDF ↓</a></div><div class="showcase-stage">{slides}<div class="showcase-controls"><span id="showcase-count" aria-live="polite">01 / {len(chosen):02}</span><button type="button" data-slide-prev aria-label="Предыдущий проект">←</button><button type="button" data-slide-next aria-label="Следующий проект">→</button></div></div><div class="showcase-tabs" role="tablist" aria-label="Выбрать проект">{tabs}</div></section>'''

def pages(g):
 page,intro,e,button=g['page'],g['intro'],g['e'],g['button'];raw=[p for p in g['CONTENT']['projects'] if p.get('published',True)];services=g['S'];settings=g['CFG']
 solutions=json.loads((g['ROOT']/'source/solutions.json').read_text())
 payload={'projects':raw,'services':services,'settings':settings,'solutions':solutions}
 options='<option value="">Все направления</option>'+''.join(f'<option value="{s["id"]}">{s["title"]}</option>' for s in services)
 types='<option value="">Все типы объектов</option>'+''.join(f'<option>{e(x)}</option>' for x in dict.fromkeys(p['type'] for p in raw))
 body=intro('География проектов','Опыт на карте.','Выберите направление и объект. Метки населённых пунктов объединяют проекты в одном городе.')
 body+=f'''<section class="section map-section"><div class="map-tools"><label>Направление<select id="map-service">{options}</select></label><label>Тип объекта<select id="map-type">{types}</select></label><label>Поиск<input id="map-search" type="search" placeholder="Объект, город или адрес"></label><button type="button" class="text-button" id="map-reset">Сбросить</button></div><p id="map-count" class="map-count" role="status"></p><div class="map-layout"><div class="map-canvas-wrap"><div id="project-map" role="region" aria-label="Карта проектов"></div><div class="map-basemap"><span id="map-message">Загрузите карту улиц или выбирайте объекты по меткам.</span><button type="button" id="map-load">Показать карту улиц</button></div><p class="map-explanation">Метки «Город» показывают населённый пункт. Адрес конкретного объекта указан в его карточке.</p><div id="map-places" class="map-places" aria-label="Населённые пункты"></div></div><div class="map-browser"><div id="map-list" aria-label="Объекты"></div><article id="map-detail"></article></div></div><noscript><p>Откройте <a href="projects.html">каталог проектов</a>, чтобы посмотреть объекты без карты.</p></noscript></section>'''+data_element(payload)
 page('map.html','Карта проектов','Объекты ФАСАД.PRO на карте: работы, фотографии и характеристики.',body,'projects')
 body=intro('Персональная подборка','Портфолио<br>под вашу задачу.','Выберите нужные объекты. Соберём единый PDF с фотографиями, составом работ и контактами компании.')
 body+=f'''<section class="section portfolio-builder"><form id="portfolio-form"><div class="portfolio-builder-top"><label>Для кого подготовить <span class="optional">необязательно</span><input name="recipient" maxlength="140" placeholder="Например, для тендерного отдела"></label><label>Направление<select id="portfolio-service">{options}</select></label><div class="portfolio-quick"><button class="text-button" type="button" id="portfolio-select">Выбрать показанные</button><button class="text-button" type="button" id="portfolio-clear">Очистить</button></div></div><div id="portfolio-cards" class="portfolio-cards"></div><div class="portfolio-builder-bottom"><div><strong id="portfolio-count" role="status"></strong><p>Порядок страниц можно изменить в подборке ниже.</p></div><button class="button" type="submit" id="portfolio-build">Скачать PDF ↓</button></div><ol id="portfolio-order" class="portfolio-order" aria-label="Порядок объектов в PDF"></ol><p id="portfolio-status" role="status" aria-live="polite"></p><div id="portfolio-ready"></div></form><p class="portfolio-alternative">Нужно полное портфолио? <a class="portfolio-download" href="downloads/portfolio.pdf" download>Скачать презентацию компании</a></p><noscript>Для сборки подборки нужен JavaScript. Полная презентация доступна по ссылке выше.</noscript></section>'''+data_element(payload)
 page('portfolio.html','Собрать портфолио','Персональное PDF-портфолио ФАСАД.PRO: выберите подходящие объекты для заказчика или тендера.',body,'projects')
 body=intro('Подбор решения','С чего начинается<br>ваша задача?','Выберите ситуацию. Покажем подходящие направления, примеры работ и список материалов для первого разговора.')
 body+='<section class="section solution-section"><div class="solution-choices" role="group" aria-label="Ваша задача">'+''.join(f'<button type="button" data-solution="{s["id"]}" aria-pressed="false"><span class="solution-number">0{i+1}</span><strong>{s["title"]}</strong><span>{s["short"]}</span><span class="solution-arrow" aria-hidden="true">↗</span></button>' for i,s in enumerate(solutions))+'</div><div id="solution-result" hidden aria-live="polite"></div><noscript>Все направления доступны на <a href="services.html">странице услуг</a>.</noscript></section>'+data_element(payload)
 page('solutions.html','Подобрать решение','Подбор фасадных работ: остекление, ремонт, протечки, замена стеклопакетов и работы на высоте.',body,'services')

def links(g):
 return '<section class="section project-tools-home"><div><p class="eyebrow">Ваш следующий объект</p><h2>Найдите похожий опыт.</h2><p>Посмотрите географию работ или соберите подборку для обсуждения с командой.</p></div><div>'+g['button']('Карта проектов','map.html')+g['button']('Собрать портфолио','portfolio.html')+'</div></section>'
