import {showLeadPane} from './lead-pane16.mjs';
import assert from 'node:assert/strict';
import path from 'node:path';

export async function verifyCRM15({page,base,shots}){
  const email='crm15-browser@example.com',phone='+7 999 000 15 15';
  await page.setViewportSize({width:390,height:844});
  await page.goto(base+'/admin/',{waitUntil:'networkidle'});
  await page.locator('#new-manual-lead').click();
  await page.locator('#manual-lead-dialog').waitFor({state:'visible'});
  await page.locator('#manual-lead-form [name=name]').fill('Клиент CRM15 <script>alert(1)</script>');
  await page.locator('#manual-lead-form [name=phone]').fill(phone);
  await page.locator('#manual-lead-form [name=email]').fill(email);
  await page.locator('#manual-lead-form [name=company]').fill('Заказчик CRM15');
  await page.locator('#manual-lead-form [name=source]').selectOption('phone');
  await page.locator('.manual-lead-extra').first().locator('summary').click();
  await page.locator('#manual-lead-form [name=city]').fill('Владивосток');
  await page.locator('#manual-lead-form [name=object]').fill('Тестовый объект CRM15');
  await page.locator('#manual-lead-form [name=services][value=glazing]').check();
  await page.locator('#manual-lead-form [name=comment]').fill('Проверка ручного обращения');
  const createdPromise=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/admin/leads'&&r.request().method()==='POST');
  await page.locator('#manual-lead-form button[type=submit]').click();
  const createdResponse=await createdPromise;assert.equal(createdResponse.status(),201,await createdResponse.text());const created=await createdResponse.json();
  await page.locator('#lead-edit').waitFor();
  assert.match(await page.locator('.lead-request-details').innerText(),/Заявка сотрудника/);
  assert.match(await page.locator('.lead-request-details').innerText(),/Телефон/);
  assert.equal(await page.locator('.lead-request-details script').count(),0,'manual contact is literal');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'manual lead fits phone');
  await page.locator('#back-leads').click();
  const openDuplicate=async()=>{
    await page.locator('#new-manual-lead').click();
    await page.locator('#manual-lead-form [name=name]').fill('Повторный контакт CRM15');
    await page.locator('#manual-lead-form [name=phone]').fill(phone);
    await page.locator('#manual-lead-form [name=email]').fill(email);
    await page.locator('#manual-lead-form [name=source]').selectOption('email');
    await page.locator('#manual-lead-form button[type=submit]').click();
    await page.locator('#manual-lead-duplicates [data-manual-existing]').first().waitFor();
    assert.match(await page.locator('#manual-lead-duplicates').innerText(),new RegExp(created.reference));
  };
  await openDuplicate();
  const beforeDuplicates=await (await page.request.get(base+'/api/admin/leads?q='+encodeURIComponent(email))).json();
  await page.locator('[data-manual-existing="'+created.id+'"]').click();await page.locator('#lead-edit').waitFor();
  const afterExisting=await (await page.request.get(base+'/api/admin/leads?q='+encodeURIComponent(email))).json();assert.equal(afterExisting.total,beforeDuplicates.total,'opening existing lead does not create another');
  await page.locator('#back-leads').click();await openDuplicate();
  const separatePromise=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/admin/leads'&&r.request().method()==='POST');
  await page.locator('#manual-allow-duplicate').click();const separate=await separatePromise;assert.equal(separate.status(),201,await separate.text());
  await page.locator('#lead-edit').waitFor();
  const afterSeparate=await (await page.request.get(base+'/api/admin/leads?q='+encodeURIComponent(email))).json();assert.equal(afterSeparate.total,beforeDuplicates.total+1,'explicit separate creates another lead');
  await page.goto(base+'/admin/#leads/'+created.id,{waitUntil:'networkidle'});await page.reload({waitUntil:'networkidle'});await page.locator('#lead-edit').waitFor();
  const internal='Заметка CRM15 остаётся внутри компании';
  await page.locator('#lead-edit [name=note]').fill(internal);
  await showLeadPane(page,'communication');
  await page.locator('#lead-history-form [name=type]').selectOption('call');
  await page.locator('#lead-history-form [name=text]').fill('Созвонились <script>alert(2)</script>, уточнили объём.');
  await page.locator('#lead-history-form button[type=submit]').click();
  await page.locator('#lead-history-status').filter({hasText:'Запись добавлена'}).waitFor();
  assert.match(await page.locator('#lead-history-list').innerText(),/Созвонились <script>alert\(2\)<\/script>/);
  assert.equal(await page.locator('#lead-history-list script').count(),0);
  assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),internal,'history preserves unsaved note');
  await showLeadPane(page,'economics');
  await page.locator('#lead-commercial-form [name=amount]').fill('995000');
  await page.locator('#lead-commercial-form button[type=submit]').click();
  await page.locator('#lead-commercial-status').filter({hasText:'Результат сделки сохранён'}).waitFor();
  assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),internal,'commercial preserves unsaved note');
  await showLeadPane(page,'quote');
  await page.locator('#lead-quote-builder>summary').click();
  const form=page.locator('#lead-quote-build');
  await form.locator('[name=title]').fill('Предложение CRM15 <script>alert(3)</script>');
  let rows=page.locator('.quote-build-item');
  await rows.first().locator('[data-item-field=title]').fill('Монтаж остекления <img src=x onerror=alert(4)>');
  await rows.first().locator('[data-item-field=unit]').fill('м²');
  await rows.first().locator('[data-item-field=quantity]').fill('10.5');
  await rows.first().locator('[data-item-field=unitPrice]').fill('98000');
  await page.locator('#quote-build-add').click();
  await rows.last().locator('[data-item-field=title]').fill('Дополнительные работы');
  await rows.last().locator('[data-item-field=unit]').fill('компл.');
  await rows.last().locator('[data-item-field=quantity]').fill('2.25');
  await rows.last().locator('[data-item-field=unitPrice]').fill('30000');
  await form.locator('[name=taxMode]').selectOption('extra');
  await form.locator('[name=taxRate]').fill('22');
  await form.locator('[name=timeframe]').fill('20 рабочих дней');
  await form.locator('[name=validUntil]').fill('2030-12-31');
  await form.locator('[name=payment]').fill('Аванс после согласования условий');
  await form.locator('[name=exclusions]').fill('Работы за пределами согласованного объёма');
  await form.locator('[name=customerNote]').fill('Комментарий заказчику CRM15');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'editable quote rows fit 390px');
  await page.screenshot({path:path.join(shots,'crm-v15-builder-mobile.png'),fullPage:true});
  const buildPromise=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/quotes/build')&&r.request().method()==='POST');
  await form.locator('button[type=submit]').click();const build=await buildPromise;assert.equal(build.status(),201,await build.text());const first=await build.json();
  await page.locator('#quote-build-status').filter({hasText:'PDF сохранён'}).waitFor();
  assert.equal(first.quote.document.totals.subtotalKopecks,109650000);assert.equal(first.quote.document.totals.taxKopecks,24123000);assert.equal(first.quote.document.totals.totalKopecks,133773000);assert.equal(first.quote.amount,'1337730.00');
  assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),internal,'builder preserves unsaved note');
  assert.equal(await page.locator('.quote-history-item').first().locator('.quote-saved-totals').count(),1,'server tax totals are shown');
  const downloadPromise=page.waitForEvent('download');await page.locator('.quote-history-item').first().locator('a[download]').click();assert.match((await downloadPromise).suggestedFilename(),/\.pdf$/);
  const replayPromise=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/quotes/build')&&r.request().method()==='POST');await form.locator('button[type=submit]').click();const replay=await replayPromise;assert.equal(replay.status(),200,'same unchanged draft uses idempotency');assert.equal((await replay.json()).quote.id,first.quote.id);
  await page.locator('.quote-history-item').first().locator('[data-quote-copy]').click();
  assert.equal(await rows.count(),2);assert.equal(await rows.first().locator('[data-item-field=quantity]').inputValue(),'10.5');assert.equal(await form.locator('[name=taxRate]').inputValue(),'22');assert.equal(await form.locator('[name=payment]').inputValue(),'Аванс после согласования условий');
  await rows.first().locator('[data-item-field=quantity]').fill('11');
  const secondPromise=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith('/quotes/build')&&r.request().method()==='POST');await form.locator('button[type=submit]').click();const secondResponse=await secondPromise;assert.equal(secondResponse.status(),201,await secondResponse.text());const second=await secondResponse.json();
  await page.locator('.quote-history-item h3').filter({hasText:'Версия 2'}).waitFor();
  assert.equal(second.quote.document.totals.totalKopecks,139751000);assert.equal(first.quote.version,1);assert.equal(second.quote.version,2);assert.equal(await page.locator('.quote-history-item').count(),2);
  await page.locator('.quote-history-item').first().locator('[data-quote-publish]').click();
  await page.locator('#lead-quote-status').filter({hasText:'Сначала создайте активную'}).waitFor();
  await page.locator('#lead-portal-issue').click();if(await page.locator('#confirm-dialog').isVisible())await page.locator('#confirm-yes').click();
  await page.locator('#lead-portal-link-result').waitFor({state:'visible'});const token=new URL(await page.locator('#lead-portal-link').inputValue()).hash.slice(1);
  await page.locator('.quote-history-item').first().locator('[data-quote-publish]').click();
  await page.locator('#lead-portal-status').filter({hasText:'КП доступно на странице заказчика'}).waitFor();
  assert.equal(await page.locator('#lead-edit [name=status]').inputValue(),'sent');
  let client=await (await page.request.get(base+'/api/client/lead',{headers:{Authorization:'Bearer '+token}})).json();
  assert.equal(client.quote.id,second.quote.id);assert.equal(client.quote.version,2);assert.equal(client.quote.amount,'1397510.00');assert.ok(!JSON.stringify(client).includes(internal),'internal draft note remains private');assert.equal(client.quote.document,undefined,'customer receives safe quote metadata');
  const view=await page.request.post(base+client.quote.viewApi,{headers:{Origin:base,Authorization:'Bearer '+token},data:{}});assert.equal(view.status(),200,await view.text());
  const file=await page.request.get(base+client.quote.downloadApi,{headers:{Authorization:'Bearer '+token}});assert.equal(file.status(),200);assert.match((await file.body()).toString('ascii',0,5),/^%PDF-/);
  await page.locator('#lead-portal-quote-refresh').click();await page.locator('#lead-portal-quote-views').filter({hasText:'PDF открыт'}).waitFor();
  assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),internal,'publication and refresh preserve unsaved note');
  await page.locator('#lead-portal-quote-withdraw').click();await page.locator('#lead-portal-status').filter({hasText:'КП убрано'}).waitFor();
  client=await (await page.request.get(base+'/api/client/lead',{headers:{Authorization:'Bearer '+token}})).json();assert.ok(!client.quote,'withdraw removes client quote');
  await page.locator('.quote-history-item').first().locator('[data-quote-publish]').click();await page.locator('#lead-portal-status').filter({hasText:'КП доступно'}).waitFor();
  await page.locator('.quote-history-item').first().locator('[data-quote-archive]').click();await page.locator('#lead-quote-status').filter({hasText:'Версия перемещена в архив'}).waitFor();
  client=await (await page.request.get(base+'/api/client/lead',{headers:{Authorization:'Bearer '+token}})).json();assert.ok(!client.quote,'archived publication is not exposed');assert.match(await page.locator('#lead-portal-quote-state').innerText(),/в архиве/);
  await page.locator('.quote-history-item').first().locator('[data-quote-archive]').click();await page.locator('#lead-quote-status').filter({hasText:'Версия возвращена'}).waitFor();
  await showLeadPane(page,'request');
  const savePromise=page.waitForResponse(r=>new URL(r.url()).pathname.startsWith('/api/admin/leads/')&&r.request().method()==='PATCH');await page.locator('#lead-edit button[type=submit]').click();const save=await savePromise;assert.equal(new URL(save.url()).pathname,'/api/admin/leads/'+created.id);assert.equal(save.status(),200,await save.text());await page.locator('#lead-save-status').filter({hasText:'Сохранено'}).waitFor();
  const final=await (await page.request.get(base+'/api/admin/leads/'+created.id)).json();assert.equal(final.note,internal);assert.equal(final.commercial.amount,'995000.00');
  await showLeadPane(page,'quote');
  assert.equal(await page.locator('#lead-quote-upload').isVisible(),true,'manual PDF upload remains usable');
  // A harmless client view can be reconciled; another employee's editable fields cannot.
  const session=await (await page.request.get(base+'/api/admin/session')).json(),foreignNote='Сотрудник изменил заметку в другой вкладке';
  const foreign=await page.request.patch(base+'/api/admin/leads/'+created.id,{headers:{Origin:base,'X-CSRF-Token':session.csrf},data:{status:'closed',note:foreignNote,assignee:'',next_contact:'',next_action:'',revision:final.revision}});
  assert.equal(foreign.status(),200,await foreign.text());
  const unsavedConflict='Моя несохранённая заметка после чужой правки';
  await showLeadPane(page,'request');
  await page.locator('#lead-edit [name=note]').fill(unsavedConflict);
  await showLeadPane(page,'communication');
  await page.locator('#lead-history-form [name=type]').selectOption('comment');
  await page.locator('#lead-history-form [name=text]').fill('Запись после изменения в другой вкладке');
  await page.locator('#lead-history-form button[type=submit]').click();
  await page.locator('#lead-save-status').filter({hasText:'Данные заявки изменились у другого сотрудника'}).waitFor();
  assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),unsavedConflict,'conflict retains manager draft');
  await showLeadPane(page,'request');
  const conflictPromise=page.waitForResponse(r=>new URL(r.url()).pathname.startsWith('/api/admin/leads/')&&r.request().method()==='PATCH');
  await page.locator('#lead-edit button[type=submit]').click();
  const conflict=await conflictPromise;assert.equal(conflict.status(),409,'changed staff fields remain protected');
  const protectedLead=await (await page.request.get(base+'/api/admin/leads/'+created.id)).json();
  assert.equal(protectedLead.note,foreignNote);assert.equal(protectedLead.assignee,'');assert.equal(protectedLead.status,'closed');
  assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),unsavedConflict);
  await showLeadPane(page,'communication');
  await page.locator('#lead-history-refresh').click();await page.locator('#lead-history-list').filter({hasText:'Созвонились'}).waitFor();
  await page.setViewportSize({width:320,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'quote workspace fits 320px');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(shots,'crm-v15-detail-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:path.join(shots,'crm-v15-detail-desktop.png'),fullPage:true});
  await page.locator('[data-tab=leads]').click();await page.locator('#confirm-dialog').waitFor({state:'visible'});await page.locator('#confirm-yes').click();await page.locator('#new-manual-lead').waitFor();
  console.log('PASS v15 CRM: manual/duplicates, timeline/commercial, exact quote totals/idempotency/copy/PDF, publication/view/withdraw/archive, unsaved note preservation, 320/390/desktop');
}
