import {showLeadPane} from './lead-pane16.mjs';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import path from 'node:path';

export async function verifyCRM14({page,base,shots}){
  const payload={kind:'quote',service:'glazing',scope:'supply-installation',object:'Коммерческое здание',city:'Владивосток',timing:'В течение 1–3 месяцев',name:'Проверка CRM v14 <script>alert(1)</script>',company:'Тестовый заказчик',phone:'+7 (995) 867-86-46',email:'crm14@example.com',projectLink:'https://example.com/crm14-project',consent:'yes',idempotency:randomUUID(),sourcePage:'/quote.html'};
  const response=await page.request.post(base+'/api/requests',{headers:{Origin:base},multipart:payload});
  assert.equal(response.status(),201,await response.text());
  const receipt=await response.json(),token=receipt.continuationUrl.split('#')[1];
  const addition=await page.request.post(base+'/api/client/lead/append',{headers:{Origin:base,Authorization:'Bearer '+token},multipart:{idempotency:randomUUID(),comment:'Материалы заказчика <script>alert(2)</script>',projectLink:'https://example.com/crm14-addition',files:{name:'addition.txt',mimeType:'text/plain',buffer:Buffer.from('Дополнение к проекту CRM')}}});
  assert.equal(addition.status(),200,await addition.text());
  const list=await (await page.request.get(base+'/api/admin/leads?q='+encodeURIComponent(receipt.reference))).json(),lead=list.rows[0];
  assert.ok(lead?.id,'created CRM lead is visible to signed-in manager');
  await page.setViewportSize({width:390,height:844});
  await page.goto(base+'/admin/',{waitUntil:'networkidle'});
  await page.locator('#lead-filter-toggle').waitFor();
  await page.locator('#lead-filter-toggle').click();
  await page.locator('#lead-search').waitFor();
  await page.locator('#lead-search [name=q]').fill('Не существует '+randomUUID());
  await page.locator('#lead-search button[type=submit]').click();
  await page.locator('.admin-empty').filter({hasText:'Заявок не найдено'}).waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'empty CRM fits mobile');
  await page.screenshot({path:path.join(shots,'crm-v14-empty-mobile.png'),fullPage:true});
  await page.locator('#lead-search [name=q]').fill(receipt.reference);
  await page.locator('#lead-search button[type=submit]').click();
  const card=page.locator('.lead-mobile-card').filter({hasText:receipt.reference});
  await card.waitFor();
  assert.equal(await page.locator('.lead-desktop-table').isHidden(),true,'mobile uses lead cards');
  assert.equal(await card.locator('a[href^="tel:"]').getAttribute('href'),'tel:+79958678646');
  assert.equal(await card.locator('a[href^="mailto:"]').getAttribute('href'),'mailto:crm14%40example.com');
  assert.equal(await card.locator('script').count(),0,'lead name is literal text');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'filled CRM fits mobile');
  await page.locator('#lead-filter-toggle').click();
  await page.screenshot({path:path.join(shots,'crm-v14-cards-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  assert.equal(await page.locator('.lead-desktop-table').isVisible(),true,'desktop keeps table');
  assert.equal(await page.locator('.lead-mobile-list').isHidden(),true);
  await page.screenshot({path:path.join(shots,'crm-v14-list-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await card.locator('[data-followup]').click();
  await page.locator('#lead-edit').waitFor();
  assert.equal(await page.evaluate(()=>document.activeElement.name),'next_action');
  assert.match(await page.locator('.lead-request-details').innerText(),/Поставка и монтаж/);
  assert.equal(await page.locator('.lead-request-details a[href="https://example.com/crm14-project"]').getAttribute('rel'),'noopener noreferrer');
  await page.locator('#lead-edit [name=next_action]').fill('Уточнить размеры');
  await page.locator('[data-contact-days="1"]').click();
  await showLeadPane(page,'request');
  await page.locator('#lead-edit button[type=submit]').click();
  await page.locator('#lead-save-status').filter({hasText:'Сохранено'}).waitFor();
  await page.locator('#lead-edit [name=note]').fill('Несохранённая внутренняя заметка CRM v14');
  const upload=async(name,amount)=>{
    await showLeadPane(page,'quote');
    await page.locator('#lead-quote-upload [name=files]').setInputFiles({name,mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF')});
    await page.locator('#lead-quote-upload [name=amount]').fill(amount);
    await page.locator('#lead-quote-upload [name=timeframe]').fill('20 рабочих дней');
    await page.locator('#lead-quote-upload [name=note]').fill('Примечание для сотрудников');
    await page.locator('#lead-quote-upload button[type=submit]').click();
    await page.locator('#lead-quote-status').filter({hasText:'Новая версия сохранена'}).waitFor();
  };
  await upload('CRM14-v1.pdf','980000');
  assert.equal(await page.locator('.quote-history-item').count(),1);
  assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),'Несохранённая внутренняя заметка CRM v14','quote upload preserves unsaved note');
  const download=page.waitForEvent('download');
  await page.locator('.quote-history-item a[download]').click();
  assert.equal((await download).suggestedFilename(),'CRM14-v1.pdf');
  await page.locator('[data-quote-send]').click();
  await page.locator('#lead-quote-status').filter({hasText:'Дата отправки сохранена'}).waitFor();
  assert.equal(await page.locator('#lead-edit [name=status]').inputValue(),'sent');
  assert.equal(await page.locator('[data-quote-send]').count(),0,'sent version cannot be sent again');
  await upload('CRM14-v2.pdf','995000');
  assert.equal(await page.locator('.quote-history-item').count(),2);
  assert.match(await page.locator('.quote-history-item').first().innerText(),/Версия 2/);
  assert.match(await page.locator('.quote-history-item').last().innerText(),/Отправлено/);
  await page.locator('.quote-history-item').first().locator('[data-quote-archive]').click();
  await page.locator('#lead-quote-status').filter({hasText:'Версия перемещена в архив'}).waitFor();
  assert.equal(await page.locator('.quote-history-item').first().locator('[data-quote-send]').count(),0,'archived draft cannot be marked sent');
  assert.match(await page.locator('.quote-history-item').first().locator('[data-quote-archive]').innerText(),/Вернуть из архива/);
  await page.locator('.quote-history-item').first().locator('[data-quote-archive]').click();
  await page.locator('#lead-quote-status').filter({hasText:'Версия возвращена из архива'}).waitFor();
  assert.equal(await page.locator('.quote-history-item').first().locator('[data-quote-send]').count(),1);
  assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),'Несохранённая внутренняя заметка CRM v14','archive preserves unsaved note');
  await showLeadPane(page,'request');
  await page.locator('#lead-edit button[type=submit]').click();
  await page.locator('#lead-save-status').filter({hasText:'Сохранено'}).waitFor();
  const afterQuote=await (await page.request.get(base+'/api/admin/leads/'+lead.id)).json();
  assert.equal(afterQuote.note,'Несохранённая внутренняя заметка CRM v14','lead revision remains valid after quote mutations');
  assert.equal(afterQuote.assignee,lead.assignee,'existing assignee remains intact');
  assert.equal(afterQuote.next_action,'Уточнить размеры');
  assert.ok(afterQuote.next_contact);
  await showLeadPane(page,'materials');
  await page.locator('.portal-update').waitFor();
  assert.match(await page.locator('.portal-update').innerText(),/Материалы заказчика <script>alert\(2\)<\/script>/);
  assert.equal(await page.locator('.portal-update script').count(),0);
  assert.equal(await page.locator('.portal-update a[href="https://example.com/crm14-addition"]').count(),1);
  assert.equal(await page.locator('.portal-update a[download]').count(),1);
  await showLeadPane(page,'quote');
  await page.locator('#lead-portal-message [name=customerMessage]').fill('Получили дополнения. Готовим расчёт.');
  await page.locator('#lead-portal-message button[type=submit]').click();
  await page.locator('#lead-portal-status').filter({hasText:'Сообщение для заказчика сохранено'}).waitFor();
  let customer=await (await page.request.get(base+'/api/client/lead',{headers:{Authorization:'Bearer '+token}})).json();
  assert.equal(customer.customerMessage,'Получили дополнения. Готовим расчёт.');
  assert.ok(!JSON.stringify(customer).includes('Несохранённая внутренняя заметка'),'internal note is private');
  await showLeadPane(page,'request');
  await page.locator('#lead-edit [name=note]').fill('Заметка сохранена после выдачи ссылки');
  await showLeadPane(page,'quote');
  await page.locator('#lead-portal-issue').click();
  await page.locator('#confirm-dialog').waitFor({state:'visible'});
  await page.locator('#confirm-yes').click();
  await page.locator('#lead-portal-link-result').waitFor({state:'visible'});
  const newLink=await page.locator('#lead-portal-link').inputValue(),newToken=new URL(newLink).hash.slice(1);
  assert.match(newLink,new RegExp('^'+base.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'/followup\\.html#[a-f0-9]{64}$'));
  assert.notEqual(newToken,token);
  assert.equal((await page.request.get(base+'/api/client/lead',{headers:{Authorization:'Bearer '+token}})).status(),404,'explicit rotation invalidates prior token');
  assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),'Заметка сохранена после выдачи ссылки');
  await page.locator('#lead-portal-copy').click();
  await page.locator('#lead-portal-status').filter({hasText:/скопирована|выделена/}).waitFor();
  await page.locator('#lead-portal-revoke').click();
  await page.locator('#confirm-yes').click();
  await page.locator('#lead-portal-status').filter({hasText:'Доступ по ссылке отключён'}).waitFor();
  assert.equal(await page.locator('#lead-portal-link-result').isHidden(),true);
  assert.equal((await page.request.get(base+'/api/client/lead',{headers:{Authorization:'Bearer '+newToken}})).status(),404,'revoke disables private link');
  await showLeadPane(page,'request');
  await page.locator('#lead-edit button[type=submit]').click();
  await page.locator('#lead-save-status').filter({hasText:'Сохранено'}).waitFor();
  const final=await (await page.request.get(base+'/api/admin/leads/'+lead.id)).json();
  assert.equal(final.note,'Заметка сохранена после выдачи ссылки','portal revisions do not invalidate manager save');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'lead workspace fits mobile');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:path.join(shots,'crm-v14-detail-mobile.png'),fullPage:true});
  await page.setViewportSize({width:320,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'lead workspace fits 320px');
  await page.setViewportSize({width:1440,height:1000});
  console.log('PASS v14 CRM: empty/mobile/cards/desktop, contacts, quote versions/download/send, preserved lead fields and revisions, private messages, additions, explicit link rotation/copy/revoke');
}
