import assert from 'node:assert/strict';
import path from 'node:path';

export async function verifyRelease14({page,base,shots}){
  await page.setViewportSize({width:390,height:844});
  await page.goto(base+'/request.html?service=glazing&scope=installation',{waitUntil:'networkidle'});
  assert.equal(await page.locator('[name=scope]').inputValue(),'installation');
  assert.match(await page.locator('#request-scope-context').innerText(),/Только монтаж/);
  await page.locator('[name=service][value=glazing]').check();
  await page.locator('[name=object]').selectOption({label:'Коммерческое здание'});
  await page.locator('[name=city]').fill('Владивосток — browser forms v14');
  await page.locator('#request-next').click();
  await page.locator('[name=projectLink]').fill('http://example.com/project');
  await page.locator('#request-next').click();
  assert.equal(await page.locator('.request-step[data-step="1"]').isVisible(),true,'insecure project links rejected');
  assert.match(await page.locator('.form-status').innerText(),/https/);
  await page.locator('[name=projectLink]').fill('https://example.com/project');
  await page.locator('#request-files').setInputFiles({name:'project.txt',mimeType:'text/plain',buffer:Buffer.from('Дополнение проекта')});
  await page.locator('#request-next').click();
  assert.match(await page.locator('#request-summary').innerText(),/Только монтаж/);
  assert.match(await page.locator('#request-summary').innerText(),/https:\/\/example.com\/project/);
  await page.locator('[name=name]').fill('Проверка интерфейса v14');
  await page.locator('[name=phone]').fill('+7 999 000 00 00');
  await page.locator('[name=consent]').check();
  let accepted=null,attempts=0;
  await page.route('**/api/requests',async route=>{attempts++;if(attempts===1){assert.equal(await page.locator('#request-transfer').isVisible(),true,'real upload feedback shown');assert.match(route.request().postData(),/name="scope"\r\n\r\ninstallation/);const response=await route.fetch();assert.equal(response.status(),201);accepted=await response.json();await route.abort('failed');}else await route.continue();});
  await page.locator('#request-next').click();
  await page.locator('.form-status').filter({hasText:'Повторите отправку'}).waitFor();
  assert.equal(await page.locator('#selected-files li').count(),1,'retry retains files');
  await page.locator('#request-next').click();
  await page.locator('#request-result').waitFor({state:'visible'});
  assert.equal(await page.locator('#result-reference').innerText(),accepted.reference);
  assert.equal(await page.locator('#request-open-continuation').getAttribute('href'),base+accepted.continuationUrl);
  await page.unroute('**/api/requests');
  await page.locator('#request-open-continuation').click();
  await page.locator('#followup-content').waitFor({state:'visible'});
  assert.equal(await page.locator('#followup-reference').innerText(),accepted.reference);
  assert.equal(await page.locator('script[src]').count(),1,'private page loads no public analytics');
  assert.equal(await page.locator('meta[name=referrer]').getAttribute('content'),'no-referrer');
  assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'noindex,nofollow,noarchive');
  await page.reload({waitUntil:'networkidle'});await page.locator('#followup-content').waitFor({state:'visible'});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'private page fits 390px');
  await page.locator('[name=comment]').fill('Комментарий для уточнения <script>alert(1)</script>');
  await page.locator('[name=projectLink]').fill('javascript:alert(1)');
  await page.locator('#followup-submit').click();
  assert.equal(await page.locator('[name=projectLink]').getAttribute('aria-invalid'),'true');
  await page.locator('[name=projectLink]').fill('https://example.com/followup');
  await page.locator('#followup-files').setInputFiles({name:'plan.txt',mimeType:'text/plain',buffer:Buffer.from('Уточнение чертежа')});
  let appendAttempts=0;
  await page.route('**/api/client/lead/append',async route=>{appendAttempts++;if(appendAttempts===1){assert.equal(await page.locator('#followup-transfer').isVisible(),true,'upload feedback remains visible while awaiting the server');const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');}else await route.continue();});
  await page.locator('#followup-submit').click();
  await page.locator('#followup-send-status').filter({hasText:'Связь прервалась'}).waitFor();
  assert.equal(await page.locator('#followup-selected-files li').count(),1);
  await page.locator('#followup-submit').click();
  await page.locator('#followup-send-status').filter({hasText:'Дополнение получено'}).waitFor();
  assert.equal(await page.locator('.followup-update').count(),1,'lost append response did not duplicate history');
  assert.match(await page.locator('.followup-update').innerText(),/Комментарий для уточнения/);
  assert.match(await page.locator('.followup-update').innerText(),/plan.txt/);
  assert.equal(await page.locator('.followup-update script').count(),0,'customer text stays literal');
  assert.match(await page.locator('.followup-update').innerText(),/<script>alert\(1\)<\/script>/);
  await page.unroute('**/api/client/lead/append');
  await page.screenshot({path:path.join(shots,'followup-v14-mobile.png'),fullPage:true});
  await page.setViewportSize({width:320,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'private page fits 320px');
  await page.goto(base+'/followup.html#'+'0'.repeat(64),{waitUntil:'networkidle'});
  await page.locator('#followup-load-status').filter({hasText:/недоступна|закончил/}).waitFor();
  assert.equal(await page.locator('#followup-content').isHidden(),true);
  assert.match(await page.locator('#followup-load-status').innerText(),/недоступна|закончил/);
  await page.goto(base+'/followup.html',{waitUntil:'networkidle'});
  await page.locator('#followup-load-status').filter({hasText:'Проверьте личную ссылку'}).waitFor();
  assert.equal(await page.locator('#followup-content').isHidden(),true);
  assert.match(await page.locator('#followup-load-status').innerText(),/Проверьте личную ссылку/);
  await page.setViewportSize({width:1440,height:1000});
  console.log('PASS v14 forms: HTTPS validation, project link receipt, upload controller, lost-response retries without duplicates, private continuation refresh, invalid tokens and mobile layout');
}
