import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import path from 'node:path';

/** Protect a manager's local calculation and make competing list reads deterministic. */
export async function verifyCrm20({page,base,shots}){
 assert.ok(['127.0.0.1','localhost','[::1]'].includes(new URL(base).hostname),'CRM fixtures require an isolated local server');
 const sessionResponse=await page.request.get(base+'/api/admin/session');assert.equal(sessionResponse.status(),200);
 const session=await sessionResponse.json(),headers={Origin:new URL(base).origin,'X-CSRF-Token':session.csrf},leads=[],templates=[];
 const api=async(route,method='GET',data)=>{const response=await page.request.fetch(base+route,{method,headers,...(data?{data}:{})});assert.ok(response.ok(),method+' '+route+': '+await response.text());return response.json();};
 const prefix='CRM20 '+randomUUID().slice(0,8);
 const create=async(label,assignee=session.username)=>{const lead=await api('/api/admin/leads','POST',{name:prefix+' '+label,email:'crm20-'+randomUUID()+'@example.test',services:['glazing'],source:'other',assignee,idempotency:randomUUID()});leads.push(lead);return lead;};
 const sourceDocument={title:'Исходная редакция CRM20',items:[{title:'Монтаж исходной редакции',unit:'м²',quantity:'2.5',unitPrice:'1234.56'}],tax:{mode:'extra',rate:'22'},timeframe:'17 рабочих дней',payment:'Оплата исходной редакции',exclusions:'Исключения исходной редакции',customerNote:'Условия исходной редакции'};
 const templateDocument={title:'Шаблон CRM20',items:[{title:'Подготовка по шаблону',unit:'шт.',quantity:'3',unitPrice:'321.09'},{title:'Монтаж по шаблону',unit:'м²',quantity:'4.25',unitPrice:'456.78'}],tax:{mode:'included',rate:'10'},timeframe:'9 рабочих дней',payment:'Оплата по шаблону',exclusions:'Исключения по шаблону',customerNote:'Условия по шаблону'};
 const settle=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const composer=()=>page.locator('#lead-quote-build').evaluate(form=>({title:form.elements.title.value,items:[...form.querySelectorAll('.quote-build-item')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-item-field]')].map(input=>[input.dataset.itemField,input.value]))),tax:{mode:form.elements.taxMode.value,rate:form.elements.taxRate.value},...Object.fromEntries(['timeframe','validUntil','payment','exclusions','customerNote'].map(field=>[field,form.elements[field].value]))}));
 const expectedDocument=document=>({title:document.title,items:document.items.map(({title,unit,quantity,unitPrice})=>({title,unit,quantity,unitPrice})),tax:{mode:document.tax.mode,rate:String(document.tax.rate)},...Object.fromEntries(['timeframe','validUntil','payment','exclusions','customerNote'].map(field=>[field,document[field]||'']))});
 let releaseHeld=null,heldPattern=null,heldHandler=null,heldCompletion=null;
 async function competingRead(pattern,predicate,start,newer,lateStatus=200){
  let used=false,notifyStarted,notifyHandled;const handled=new Promise(resolve=>{notifyHandled=resolve;}),started=new Promise(resolve=>{notifyStarted=resolve;}),held=new Promise(resolve=>{releaseHeld=resolve;});
  const handler=async intercepted=>{if(used||!predicate(new URL(intercepted.request().url()))){await intercepted.continue();return;}used=true;const actual=await intercepted.fetch();notifyStarted();await held;if(lateStatus===200)await intercepted.fulfill({response:actual});else await intercepted.fulfill({status:lateStatus,contentType:'application/json',json:{error:'Старая ошибка CRM20'}});notifyHandled();};
  heldPattern=pattern;heldHandler=handler;heldCompletion=handled;await page.route(pattern,handler);await start();await started;await newer();
  const late=page.waitForResponse(response=>predicate(new URL(response.url())));releaseHeld();releaseHeld=null;await late;await handled;await settle();await page.unroute(pattern,handler);heldPattern=null;heldHandler=null;heldCompletion=null;
 }
 const allWrites=[];const trackWrites=request=>{if(request.url().startsWith(base+'/api/')&&request.method()!=='GET')allWrites.push(request.url());};
 try{
  const primary=await create('Альфа'),other=await create('Бета',''),route='/api/admin/leads/'+primary.id;
  const first=(await api(route+'/quotes/build','POST',{...sourceDocument,idempotency:randomUUID()})).quote;
  const template=(await api('/api/admin/quote-templates','POST',{name:prefix+' шаблон',serviceIds:['glazing'],document:templateDocument,idempotency:randomUUID()})).template;templates.push(template);
  const before=await api(route),quotesBefore=await api(route+'/quotes');
  await page.setViewportSize({width:390,height:844});await page.goto(base+'/admin/#leads/'+primary.id,{waitUntil:'networkidle'});await page.reload({waitUntil:'networkidle'});await page.locator('#quote-template16-select').waitFor({state:'attached'});await page.waitForFunction(id=>document.querySelector('#quote-template16-select option[value="'+id+'"]'),template.id);
  await page.locator('#lead-edit [name=note]').fill('Заметка остаётся при замене только конструктора CRM20');await page.locator('[data-lead-pane=quote]').click();
  page.on('request',trackWrites);
  const copy=page.locator('[data-quote-copy="'+first.id+'"]');await copy.click();await settle();
  assert.equal(await page.locator('#confirm-dialog').isVisible(),false,'unrelated management note does not trigger quote replacement confirmation');assert.deepEqual(await composer(),expectedDocument(first.document));
  const form=page.locator('#lead-quote-build');await form.locator('[name=title]').fill('Мой несохранённый расчёт CRM20');await form.locator('[name=taxMode]').selectOption('included');await form.locator('[name=taxRate]').fill('20');await form.locator('[name=payment]').fill('Моя схема оплаты');await form.locator('[name=exclusions]').fill('Мои исключения');await form.locator('[name=customerNote]').fill('Мои условия');await form.locator('[name=timeframe]').fill('Мой срок');await form.locator('[name=validUntil]').fill('2032-01-02');await page.locator('#quote-build-add').click();
  const added=page.locator('.quote-build-item').last();await added.locator('[data-item-field=title]').fill('Моя дополнительная позиция');await added.locator('[data-item-field=unit]').fill('шт.');await added.locator('[data-item-field=quantity]').fill('7');await added.locator('[data-item-field=unitPrice]').fill('89.10');
  const draft=await composer();allWrites.length=0;await copy.click();await page.locator('#confirm-dialog').waitFor({state:'visible'});assert.match(await page.locator('#confirm-text').innerText(),/конструкторе КП/);await page.locator('#confirm-cancel').click();assert.deepEqual(await composer(),draft,'cancel keeps every row, VAT and condition');assert.equal(allWrites.length,0,'copy cancellation performs no API write');
  await copy.click();await page.locator('#confirm-dialog').waitFor({state:'visible'});await page.locator('#confirm-yes').click();await settle();assert.deepEqual(await composer(),expectedDocument(first.document),'accepted replacement copies the chosen historical version');assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),'Заметка остаётся при замене только конструктора CRM20');assert.equal(allWrites.length,0,'copy is local even after confirmation');
  await page.locator('#quote-template16-select').selectOption(template.id);const oldStatus=await page.locator('#quote-template16-status').innerText(),beforeTemplate=await composer();await page.locator('#quote-template16-apply').click();await page.locator('#confirm-dialog').waitFor({state:'visible'});await page.locator('#confirm-cancel').click();assert.deepEqual(await composer(),beforeTemplate,'template cancellation keeps the current draft');assert.equal(await page.locator('#quote-template16-status').innerText(),oldStatus,'cancelled transfer never announces success');assert.equal(allWrites.length,0);
  await page.locator('#quote-template16-apply').click();await page.locator('#confirm-dialog').waitFor({state:'visible'});await page.locator('#confirm-yes').click();await page.locator('#quote-template16-status').filter({hasText:'перенесён'}).waitFor();assert.deepEqual(await composer(),expectedDocument(template.document),'accepted transfer copies its template, not the old offer');assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),'Заметка остаётся при замене только конструктора CRM20');assert.equal(allWrites.length,0);
  assert.equal((await api(route)).revision,before.revision);assert.equal((await api(route+'/quotes')).quotes.length,quotesBefore.quotes.length,'draft replacements never create or publish PDFs');
  if(shots)await page.locator('#lead-quote-builder').screenshot({path:path.join(shots,'crm20-protected-composer-mobile.png')});
  const savedResponse=page.waitForResponse(response=>response.url()===base+route+'/quotes/build'&&response.request().method()==='POST');await form.locator('button[type=submit]').click();assert.equal((await savedResponse).status(),201);await page.locator('#quote-build-status').filter({hasText:'PDF сохранён'}).waitFor();
  allWrites.length=0;await copy.click();await settle();assert.equal(await page.locator('#confirm-dialog').isVisible(),false,'successful PDF creation updates the constructor baseline');assert.deepEqual(await composer(),expectedDocument(first.document));assert.equal(allWrites.length,0);
  await page.locator('[data-tab=leads]').click();await page.locator('#confirm-dialog').waitFor({state:'visible'});await page.locator('#confirm-cancel').click();assert.equal(await page.locator('#lead-edit [name=note]').inputValue(),'Заметка остаётся при замене только конструктора CRM20','existing navigation cancellation still protects the management draft');await page.locator('[data-tab=leads]').click();await page.locator('#confirm-yes').click();await page.locator('#new-manual-lead').waitFor();page.off('request',trackWrites);

  const showFilters=async()=>{if(!await page.locator('#lead-search [name=q]').isVisible())await page.locator('#lead-filter-toggle').click();};
  const search=async q=>{await showFilters();await page.locator('#lead-search [name=q]').fill(q);await page.locator('#lead-search [name=status]').selectOption('');await page.locator('#lead-search [name=assignee]').selectOption('');await page.locator('#lead-search [name=due]').selectOption('');await page.locator('#lead-search [name=incoming]').selectOption('');await page.locator('#lead-search button[type=submit]').click();};
  const beta=()=>page.locator('.lead-mobile-list .lead-card-reference[data-lead="'+other.id+'"]');
  for(const lateStatus of [200,500]){
   await competingRead(base+'/api/admin/leads?*',url=>url.searchParams.get('q')===prefix+' Альфа',()=>search(prefix+' Альфа'),async()=>{await search(prefix+' Бета');await beta().waitFor();},lateStatus);
   assert.equal(await page.locator('#lead-search [name=q]').inputValue(),prefix+' Бета');assert.equal(await beta().count(),1);assert.equal(await page.locator('.lead-mobile-list [data-lead="'+primary.id+'"]').count(),0,'older search cannot replace newer rows');assert.equal(await page.locator('#admin-status.error').count(),0,'older search error cannot replace current status');assert.equal(await page.locator('#lead-search button[type=submit]').isEnabled(),true);
  }
  // A delayed error from a section that has been left must not replace the new tab.
  await competingRead(base+'/api/admin/leads?*',url=>url.searchParams.get('q')===prefix+' Альфа',()=>search(prefix+' Альфа'),async()=>{await page.locator('[data-tab=incoming]').click();await page.locator('#incoming-refresh').waitFor();},500);assert.equal(await page.locator('#incoming-refresh').count(),1);assert.equal(await page.locator('#admin-status.error').count(),0);

  const append=async(lead,comment)=>{const portalRoute='/api/admin/leads/'+lead.id+'/portal';let portal=await api(portalRoute);portal=await api(portalRoute,'POST',{action:'issue',revision:portal.revision});const token=new URL(portal.url,base).hash.slice(1);const response=await page.request.post(base+'/api/client/lead/append',{headers:{Origin:new URL(base).origin,Authorization:'Bearer '+token},multipart:{idempotency:randomUUID(),comment}});assert.equal(response.status(),200,await response.text());};
  await append(primary,prefix+' мои материалы');await append(other,prefix+' неназначенные материалы');await page.locator('#incoming-refresh').click();await page.locator('#incoming-list').filter({hasText:prefix+' неназначенные материалы'}).waitFor();
  const minePredicate=url=>url.searchParams.get('limit')==='100'&&url.searchParams.get('mine')==='0';
  for(const lateStatus of [200,500,401]){
   await page.locator('#incoming-mine').check();await page.waitForFunction(()=>!document.querySelector('#incoming-list')?.textContent.includes('неназначенные материалы'));
   await competingRead(base+'/api/admin/incoming?*',minePredicate,()=>page.locator('#incoming-mine').uncheck(),async()=>{await page.locator('#incoming-mine').check();await page.locator('#incoming-list').filter({hasText:prefix+' мои материалы'}).waitFor();await page.waitForFunction(text=>!document.querySelector('#incoming-list')?.textContent.includes(text),prefix+' неназначенные материалы');},lateStatus);
   assert.equal(await page.locator('#incoming-mine').isChecked(),true,'older all-incoming read cannot reset mine choice');assert.ok(!(await page.locator('#incoming-list').innerText()).includes(prefix+' неназначенные материалы'));assert.equal(await page.locator('#admin-status.error').count(),0);assert.equal(await page.locator('#admin-shell').isVisible(),true,'older unauthorized read cannot end a newer valid view');
  }
  const unassignedEvent=(await api('/api/admin/incoming?mine=0&limit=100&offset=0')).entries.find(entry=>entry.leadId===other.id&&entry.comment===prefix+' неназначенные материалы');assert.ok(unassignedEvent);await page.locator('#incoming-mine').uncheck();await page.locator('[data-incoming-id="'+unassignedEvent.id+'"]').waitFor();
  await competingRead(base+'/api/admin/incoming/'+unassignedEvent.id,()=>true,()=>page.locator('[data-incoming-id="'+unassignedEvent.id+'"] [data-incoming-process]').click(),async()=>{await page.locator('#incoming-mine').check();await page.waitForFunction(id=>!document.querySelector('[data-incoming-id="'+id+'"]'),unassignedEvent.id);});
  assert.equal(await page.locator('#incoming-mine').isChecked(),true,'a completed PUT cannot reload a captured older mine filter');assert.equal(await page.locator('[data-incoming-id="'+unassignedEvent.id+'"]').count(),0);
  const incomingEvent=(await api('/api/admin/incoming?mine=1&limit=100&offset=0')).entries.find(entry=>entry.leadId===primary.id&&entry.comment===prefix+' мои материалы');assert.ok(incomingEvent);
  await competingRead(base+'/api/admin/incoming/'+incomingEvent.id,()=>true,()=>page.locator('[data-incoming-id="'+incomingEvent.id+'"] [data-incoming-process]').click(),async()=>{await page.locator('[data-tab=stats]').click();await page.locator('#stats-days').waitFor();});
  assert.equal(await page.locator('#stats-days').count(),1,'a completed incoming PUT cannot reload a list after its view was left');assert.equal(await page.locator('#incoming-mine').count(),0);
  await page.locator('[data-tab=day]').click();await page.locator('#day-refresh').waitFor();
  let fresh=null;
  await competingRead(base+'/api/admin/day',()=>true,()=>page.locator('#day-refresh').click(),async()=>{fresh=await create('Новый день');await page.locator('#day-refresh').click();await page.locator('#day-new [data-lead="'+fresh.id+'"]').waitFor();});
  assert.equal(await page.locator('#day-new [data-lead="'+fresh.id+'"]').count(),1,'older day snapshot cannot hide a newly assigned lead');const dayCount=await page.locator('[data-day-count=new]').innerText();
  await competingRead(base+'/api/admin/day',()=>true,()=>page.locator('#day-refresh').click(),async()=>{const latest=page.waitForResponse(response=>response.url()===base+'/api/admin/day');await page.locator('#day-refresh').click();await latest;await settle();},500);assert.equal(await page.locator('[data-day-count=new]').innerText(),dayCount);assert.equal(await page.locator('#admin-status.error').count(),0);assert.equal(await page.locator('#day-refresh').isEnabled(),true);
  const currentFailure=async intercepted=>intercepted.fulfill({status:500,contentType:'application/json',json:{error:'Актуальная ошибка CRM20'}});await page.route(base+'/api/admin/day',currentFailure);await page.locator('#day-refresh').click();await page.locator('#admin-status.error').filter({hasText:'Актуальная ошибка CRM20'}).waitFor();await page.unroute(base+'/api/admin/day',currentFailure);const retry=page.waitForResponse(response=>response.url()===base+'/api/admin/day');await page.locator('#day-refresh').click();assert.equal((await retry).status(),200,'visible refresh remains usable after the latest failure');await settle();assert.equal(await page.locator('#admin-status.error').count(),0,'a successful direct retry clears its previous list error without leaving the tab');await page.evaluate(()=>status('Результат обработки сохранён CRM20'));const keepMutationStatus=page.waitForResponse(response=>response.url()===base+'/api/admin/day');await page.locator('#day-refresh').click();await keepMutationStatus;await settle();assert.equal(await page.locator('#admin-status').innerText(),'Результат обработки сохранён CRM20','a list success does not erase a separate action status');await page.locator('[data-tab=day]').click();await page.locator('#day-refresh').waitFor();assert.equal(await page.locator('#admin-status.error').count(),0,'latest failures still surface and tab reload recovers');
  for(const width of [320,390,1440]){await page.setViewportSize({width,height:width===1440?1000:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'CRM day fits '+width);}
  console.log('PASS CRM20: constructor-only replacement guard, both cancellation/source flows, saved-PDF baseline and management drafts; real out-of-order search/incoming/day reads, stale success/500/401 and section errors ignored, 320/390/1440 widths');
 }catch(error){console.log('CRM20 assertion failure:',error.message);throw error;}finally{
  page.off('request',trackWrites);releaseHeld?.();if(heldPattern){await heldCompletion;await page.unroute(heldPattern,heldHandler);}
  for(const template of templates){const current=(await api('/api/admin/quote-templates')).templates.find(item=>item.id===template.id);if(current)await api('/api/admin/quote-templates/'+template.id,'DELETE',{revision:current.revision,idempotency:randomUUID()});}
  for(const lead of leads){const removed=await page.request.delete(base+'/api/admin/leads/'+lead.id,{headers});assert.equal(removed.status(),200,'remove isolated CRM20 fixture');}
 }
}
