import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import path from 'node:path';

/** Verify the manager's work queue and per-employee processing against persisted events. */
export async function verifyDay16({page,base,shots}){
  assert.ok(['127.0.0.1','localhost','[::1]'].includes(new URL(base).hostname),'day fixtures require an isolated local server');
  const session=await (await page.request.get(base+'/api/admin/session')).json(),headers={Origin:new URL(base).origin,'X-CSRF-Token':session.csrf},ids=[];
  const get=async route=>{const response=await page.request.get(base+route);assert.equal(response.status(),200,await response.text());return response.json();};
  const baseline=await get('/api/admin/day'),today=baseline.today,previous=new Date(today+'T12:00:00Z');previous.setUTCDate(previous.getUTCDate()-1);const overdue=previous.toISOString().slice(0,10);
  async function create(name,assignee=session.username,next_contact='',next_action=''){
    const response=await page.request.post(base+'/api/admin/leads',{headers,data:{name,email:'day16-'+randomUUID()+'@example.test',services:['glazing'],source:'other',assignee,next_contact,next_action,idempotency:randomUUID()}});assert.equal(response.status(),201,await response.text());const created=await response.json();ids.push(created.id);return created;
  }
  async function addition(created,comment,withFile=false){
    let portal=await get('/api/admin/leads/'+created.id+'/portal');const response=await page.request.post(base+'/api/admin/leads/'+created.id+'/portal',{headers,data:{action:'issue',revision:portal.revision}});assert.equal(response.status(),200,await response.text());portal=await response.json();const token=new URL(portal.url,base).hash.slice(1);
    const sent=await page.request.post(base+'/api/client/lead/append',{headers:{Origin:new URL(base).origin,Authorization:'Bearer '+token},multipart:{idempotency:randomUUID(),comment,projectLink:'https://example.test/materials',...(withFile?{files:{name:'day16-materials.txt',mimeType:'text/plain',buffer:Buffer.from('Материалы для isolated browser fixture')}}:{})}});assert.equal(sent.status(),200,await sent.text());
  }
  async function quoteResponse(created){
    const route='/api/admin/leads/'+created.id,upload=await page.request.post(base+route+'/quotes',{headers,multipart:{amount:'10000.50',timeframe:'20 рабочих дней',note:'Внутренние условия CRM16',idempotency:randomUUID(),files:{name:'day16-offer.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n% isolated browser fixture\n%%EOF\n')}}});assert.equal(upload.status(),201,await upload.text());const {quote}=await upload.json();
    let portal=await get(route+'/portal');const issued=await page.request.post(base+route+'/portal',{headers,data:{action:'issue',revision:portal.revision}});assert.equal(issued.status(),200,await issued.text());portal=await issued.json();const token=new URL(portal.url,base).hash.slice(1),published=await page.request.post(base+route+'/portal',{headers,data:{action:'publishQuote',quoteId:quote.id,revision:portal.revision}});assert.equal(published.status(),200,await published.text());
    const comment='Пересчёт КП16 <svg onload="window.day16Xss=true">';const response=await page.request.post(base+'/api/client/lead/quotes/'+quote.id+'/response',{headers:{Origin:new URL(base).origin,Authorization:'Bearer '+token},data:{quoteId:quote.id,choice:'reprice',comment,idempotency:randomUUID()}});assert.equal(response.status(),200,await response.text());return {comment,quote};
  }
  try{
    const late=await create('Просрочено CRM16',session.username,overdue,'Связаться по просроченному объекту'),due=await create('Сегодня CRM16',session.username,today,'Связаться сегодня'),fresh=await create('Новое CRM16 <img src=x onerror="window.day16Xss=true">'),unassigned=await create('Не назначено CRM16','',today,'Не в моём дне'),finished=await create('Завершено CRM16',session.username,today,'Завершённый контакт'),quoted=await create('Ответ по КП CRM16');
    const closedDetail=await get('/api/admin/leads/'+finished.id),closed=await page.request.patch(base+'/api/admin/leads/'+finished.id,{headers,data:{revision:closedDetail.revision,status:'won',note:closedDetail.note,assignee:closedDetail.assignee,next_contact:closedDetail.next_contact,next_action:closedDetail.next_action}});assert.equal(closed.status(),200,await closed.text());
    const hostile='Вопрос CRM16 <script>window.day16Xss=true</script>';await addition(fresh,hostile,true);await addition(unassigned,'Вопрос по неназначенной заявке CRM16');const quoteReply=await quoteResponse(quoted);
    const day=await get('/api/admin/day');assert.equal(day.timezone,'Asia/Vladivostok');assert.equal(day.today,today);assert.ok(day.groups.overdue.some(entry=>entry.id===late.id));assert.ok(day.groups.today.some(entry=>entry.id===due.id));assert.ok(day.groups.new.some(entry=>entry.id===fresh.id));
    for(const entries of Object.values(day.groups))assert.ok(!entries.some(entry=>entry.id===unassigned.id||entry.leadId===unassigned.id),'my day excludes unassigned lead');assert.ok(!day.groups.today.some(entry=>entry.id===finished.id),'won is excluded from contact queues');
    assert.equal(day.counts.overdue,baseline.counts.overdue+1);assert.equal(day.counts.today,baseline.counts.today+1);assert.equal(day.counts.new,baseline.counts.new+3);assert.equal(day.counts.incoming,baseline.counts.incoming+2);
    const inbox=await get('/api/admin/incoming?mine=0&limit=100&offset=0'),mine=await get('/api/admin/incoming?mine=1&limit=100&offset=0'),incoming=inbox.entries.find(entry=>entry.leadId===fresh.id),other=inbox.entries.find(entry=>entry.leadId===unassigned.id),responseEvent=inbox.entries.find(entry=>entry.leadId===quoted.id&&entry.kind==='quote_response');assert.ok(incoming&&other&&responseEvent);assert.equal(incoming.filesCount,1);assert.equal(responseEvent.choice,'reprice');assert.equal(responseEvent.quoteVersion,1);assert.ok(day.groups.incoming.some(entry=>entry.id===responseEvent.id));assert.ok(mine.entries.some(entry=>entry.id===incoming.id));assert.ok(!mine.entries.some(entry=>entry.id===other.id));
    await page.setViewportSize({width:390,height:844});await page.goto(base+'/admin/',{waitUntil:'networkidle'});await page.locator('[data-tab=day]').click();await page.locator('[data-lead="'+late.id+'"]').first().waitFor();
    for(const [key,count] of Object.entries(day.counts))assert.equal(await page.locator('[data-day-count="'+key+'"]').innerText(),String(count),'displayed day count '+key);
    assert.match(await page.locator('#admin-view').innerText(),/Просрочено|Просроченные/);assert.match(await page.locator('#admin-view').innerText(),/Сегодня/);assert.match(await page.locator('#admin-view').innerText(),/Новое CRM16/);assert.equal(await page.locator('#admin-view script').count(),0);assert.equal(await page.evaluate(()=>window.day16Xss),undefined);assert.equal(await page.locator('[data-lead="'+unassigned.id+'"]').count(),0);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'my day fits phone');await page.screenshot({path:path.join(shots,'day16-mobile.png'),fullPage:true});
    await page.locator('[data-lead="'+due.id+'"]').first().click();await page.locator('#lead-edit').waitFor();assert.match(await page.locator('#admin-view').innerText(),new RegExp(due.reference));
    assert.ok(await page.evaluate(()=>{const tabs=document.querySelector('.lead-pane-tabs');return tabs.scrollWidth<=tabs.clientWidth+1&&[...tabs.querySelectorAll('[data-lead-pane]')].every(button=>button.scrollWidth<=button.clientWidth+1);}), 'all five pane labels fit 390px');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(shots,'crm16-mobile-final.png'),fullPage:true});
    await page.locator('[data-tab=incoming]').click();const card=page.locator('[data-incoming-id="'+incoming.id+'"]');await card.waitFor();assert.ok((await card.innerText()).includes(hostile));assert.equal(await card.locator('script').count(),0);assert.equal(await page.evaluate(()=>window.day16Xss),undefined);assert.match(await card.innerText(),/1/);
    const responseCard=page.locator('[data-incoming-id="'+responseEvent.id+'"]');await responseCard.waitFor();const responseText=await responseCard.innerText();assert.match(responseText,/КП 1/);assert.match(responseText,/пересчёт|пересчет/i);assert.ok(responseText.includes(quoteReply.comment),'quote response comment is literal');assert.ok(!responseText.includes('Внутренние условия CRM16'));assert.equal(await responseCard.locator('svg').count(),0);assert.equal(await page.evaluate(()=>window.day16Xss),undefined);
    await page.locator('#incoming-mine').check();await card.waitFor();await page.waitForFunction(id=>!document.querySelector('[data-incoming-id="'+id+'"]'),other.id);assert.equal(await page.locator('[data-incoming-id="'+other.id+'"]').count(),0,'mine filter removes unassigned events');
    const leadBefore=await get('/api/admin/leads/'+fresh.id),markPromise=page.waitForResponse(response=>new URL(response.url()).pathname.includes('/incoming/'+incoming.id)&&response.request().method()!=='GET');await card.locator('[data-incoming-process]').click();const marked=await markPromise;assert.equal(marked.status(),200,await marked.text());
    const afterInbox=await get('/api/admin/incoming?mine=1&limit=100&offset=0'),afterEvent=afterInbox.entries.find(entry=>entry.id===incoming.id);assert.equal(afterEvent.processed,true);assert.equal(afterEvent.processedBy,session.username);assert.equal(afterInbox.unread,mine.unread-1);assert.equal((await get('/api/admin/leads/'+fresh.id)).revision,leadBefore.revision,'processing does not pretend to change customer/project data');const allAfterInbox=await get('/api/admin/incoming?mine=0&limit=100&offset=0');await page.waitForFunction(count=>document.querySelector('#incoming-badge')?.textContent===String(count),allAfterInbox.unread);
    await page.locator('[data-tab=day]').click();await page.locator('[data-lead="'+late.id+'"]').first().waitFor();assert.equal(await page.locator('[data-incoming-id="'+incoming.id+'"]').count(),0,'processed event leaves my day');
    for(const width of [320,1440]){await page.setViewportSize({width,height:width===1440?1000:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'my day fits '+width);if(width===1440)await page.screenshot({path:path.join(shots,'day16-desktop.png'),fullPage:true});}
    await page.locator('[data-tab=incoming]').click();await page.locator('#incoming-mine').uncheck();const otherCard=page.locator('[data-incoming-id="'+other.id+'"]');await otherCard.waitFor();
    const foreign=await page.request.put(base+'/api/admin/incoming/'+other.id,{headers,data:{revision:other.revision,processed:true}});assert.equal(foreign.status(),200,await foreign.text());
    const conflictPromise=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/admin/incoming/'+other.id&&response.request().method()==='PUT');await otherCard.locator('[data-incoming-process]').click();assert.equal((await conflictPromise).status(),409,'stale tab cannot overwrite incoming mark');await otherCard.locator('[data-incoming-status]').filter({hasText:'другой вкладке'}).waitFor();assert.equal((await get('/api/admin/incoming?mine=0&limit=100&offset=0')).entries.find(entry=>entry.id===other.id).processed,true);
    await page.locator('#incoming-refresh').click();await otherCard.locator('[data-incoming-process]').filter({hasText:'Вернуть'}).waitFor();const undoPromise=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/admin/incoming/'+other.id&&response.request().method()==='PUT');await otherCard.locator('[data-incoming-process]').click();assert.equal((await undoPromise).status(),200);await otherCard.locator('[data-incoming-process]').filter({hasText:'Обработано'}).waitFor();assert.equal((await get('/api/admin/incoming?mine=0&limit=100&offset=0')).entries.find(entry=>entry.id===other.id).processed,false,'employee may return an event to their inbox');
    for(const width of [390,320,1440]){await page.setViewportSize({width,height:width===1440?1000:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'incoming fits '+width);if(width!==320)await page.screenshot({path:path.join(shots,'incoming16-'+(width===390?'mobile':'desktop')+'.png'),fullPage:true});}
    await page.locator('[data-tab=leads]').click();await page.locator('#lead-search').waitFor();const showFilters=async()=>{if(!await page.locator('#lead-search [name=incoming]').isVisible())await page.locator('#lead-filter-toggle').click();};await showFilters();await page.locator('#lead-search [name=incoming]').selectOption('1');
    const filteredPromise=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/admin/leads'&&new URL(response.url()).searchParams.get('incoming')==='1');await page.locator('#lead-search button[type=submit]').click();assert.equal((await filteredPromise).status(),200);await page.locator('.lead-desktop-table [data-lead="'+quoted.id+'"]').waitFor();assert.equal(await page.locator('.lead-desktop-table [data-lead="'+fresh.id+'"]').count(),0,'processed-only lead leaves Require answer filter');assert.equal(await page.locator('.lead-desktop-table [data-lead="'+unassigned.id+'"]').count(),1);assert.match(await page.locator('.lead-desktop-table tr').filter({has:page.locator('[data-lead="'+quoted.id+'"]')}).innerText(),/Новые: 1/);
    const privateQuery='+7 999 123 45 67';await page.locator('#lead-search [name=q]').fill(privateQuery);const queryPromise=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/admin/leads'&&new URL(response.url()).searchParams.get('q')===privateQuery);await page.locator('#lead-search button[type=submit]').click();await queryPromise;
    const storageKey='facadepro.crm16.filters.'+encodeURIComponent(session.username),stored=await page.evaluate(key=>localStorage.getItem(key),storageKey);assert.ok(stored&&!stored.includes(privateQuery));assert.deepEqual(Object.keys(JSON.parse(stored)).sort(),['assignee','due','incoming','status']);assert.equal(JSON.parse(stored).incoming,'1');
    await page.reload({waitUntil:'networkidle'});await page.locator('#lead-search').waitFor();assert.equal(await page.locator('#lead-search [name=incoming]').inputValue(),'1','non-contact filters survive reload');assert.equal(await page.locator('#lead-search [name=q]').inputValue(),'','contact search is not persisted');await showFilters();const resetPromise=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/admin/leads'&&new URL(response.url()).searchParams.get('incoming')==='');await page.locator('#lead-filter-reset').click();assert.equal((await resetPromise).status(),200);assert.equal(JSON.parse(await page.evaluate(key=>localStorage.getItem(key),storageKey)).incoming,'');
    const guest=await page.context().browser().newContext();try{const unsigned=await guest.newPage();assert.equal((await unsigned.request.get(base+'/api/admin/day')).status(),401);assert.equal((await unsigned.request.get(base+'/api/admin/incoming')).status(),401);}finally{await guest.close();}
    console.log('PASS day16: Vladivostok dates, assigned-only queues, real additions/files/quote responses, literal text, mine filter, processing/conflict/undo/badges, Require answer filter and contact-free persistence, guest protection, 320/390/1440 widths');
  }finally{for(const id of ids){const response=await page.request.delete(base+'/api/admin/leads/'+id,{headers});assert.equal(response.status(),200,'remove isolated day fixture');}}
}
