import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import {createBudget} from '../backend/budget14.mjs';
const db=new DatabaseSync(':memory:');
const fail=(status,message)=>Object.assign(Error(message),{status});
const text=(value,max,required=false)=>{if(typeof value!=='string'||value.length>max||required&&!value.trim())throw fail(422,'text');return value.trim();};
const actions=[],budget=createBudget({db,fail,text,audit:(...args)=>actions.push(args)});
const input={service:'glazing',scope:'installation',area:100,region:'vladivostok',height:'low'};
assert.equal(budget.config().configured,false);
assert.equal(budget.estimate(input).available,false);
assert.throws(()=>budget.estimate({...input,area:NaN}),{status:422});
assert.throws(()=>budget.estimate({...input,scope:'all'}),{status:422});
const c=budget.config();
const next={...c,rates:[{service:'glazing',scope:'installation',min:100,max:200}],regions:c.regions.map(r=>({...r,multiplier:1.5})),heights:c.heights};
const saved=budget.save(next,'manager');
assert.equal(saved.revision,2);
assert.equal(saved.configured,true);
assert.deepEqual([budget.estimate(input).min,budget.estimate(input).max],[15000,30000]);
assert.equal(budget.estimate({...input,scope:'supply-installation'}).available,false);
assert.throws(()=>budget.save(next,'manager'),{status:409});
assert.throws(()=>budget.save({...saved,rates:[{service:'glazing',scope:'installation',min:200,max:100}]},'manager'),{status:422});
assert.throws(()=>budget.save({...saved,rates:[{service:'glazing',scope:'installation',min:0,max:100}]},'manager'),{status:422});
assert.throws(()=>budget.save({...saved,rates:[{service:'glazing',scope:'installation',min:0.001,max:100}]},'manager'),{status:422});
assert.equal(actions.length,1);
assert.equal(budget.config().revision,2);
budget.save({...saved,rates:[]},'manager');
assert.equal(budget.estimate(input).available,false);
db.close();console.log('Budget: empty/configured prices, calculations, invalid inputs and conflicting edits passed');
