import {DatabaseSync} from 'node:sqlite';
import {randomUUID,createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {createCRM15,validateAttribution} from '../backend/crm15.mjs';

const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE leads(id TEXT PRIMARY KEY,reference TEXT UNIQUE NOT NULL,created TEXT NOT NULL,kind TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'new',payload TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',revision INTEGER NOT NULL DEFAULT 1,idempotency TEXT UNIQUE NOT NULL,digest TEXT NOT NULL,session_id TEXT,assignee TEXT NOT NULL DEFAULT '',next_contact TEXT NOT NULL DEFAULT '',next_action TEXT NOT NULL DEFAULT '');
CREATE TABLE quote_versions(id TEXT PRIMARY KEY,lead_id TEXT NOT NULL REFERENCES leads(id) ON DELETE CASCADE);
CREATE TABLE outbox(id TEXT PRIMARY KEY,lead_id TEXT REFERENCES leads(id) ON DELETE CASCADE);`);
const fail=(status,message)=>Object.assign(Error(message),{status}),text=(s,max,required=false)=>{if(typeof s!=='string'||s.length>max||required&&!s.trim()||/[\u0000-\u001f]/.test(s))throw fail(422,'text');return s.trim();},atomic=fn=>{db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}};
const clock={stamp:'2026-10-07T03:00:00.000Z'},actions=[];
const options={db,fail,text,emailOK:s=>/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(s),SERVICE_IDS:['glazing','windows','repair','engineering','supply','height'],STATUSES:{new:'Новая',review:'На рассмотрении',estimate:'Готовим КП',sent:'КП отправлено',won:'Договор',closed:'Закрыта'},audit:(...args)=>actions.push(args),transaction:atomic,hash:s=>createHash('sha256').update(s).digest('hex'),staff:()=>['manager','other'],now:()=>new Date(clock.stamp)};
const crm=createCRM15(options);
const seed=(payload={},overrides={})=>{const id=randomUUID();db.prepare('INSERT INTO leads(id,reference,created,kind,status,payload,idempotency,digest) VALUES(?,?,?,?,?,?,?,?)').run(id,'FP-SEED-'+id,overrides.created||'2026-10-06T03:00:00.000Z','request',overrides.status||'new',JSON.stringify({name:'Old client',phone:'',email:'',services:[],...payload}),randomUUID(),'legacy');return id;};
const legacy=seed({name:'Существующий клиент',phone:'8 (999) 123-45-67',email:'OWNER@EXAMPLE.COM'});
assert.equal(crm.history(legacy).entries.length,0,'migration invents no past history');assert.deepEqual(crm.commercial(legacy),{amount:'',lossReason:'',revision:0,leadRevision:1,leadStatus:'new'});
const manual={idempotency:randomUUID(),name:'Новый проект',phone:'+7 999 123 45 67',email:'owner@example.com',source:'phone',services:[],assignee:'manager',comment:'Новый объект'};
let duplicate;try{crm.create(manual,'manager');}catch(error){duplicate=error;}assert.equal(duplicate.status,409);assert.deepEqual(duplicate.matches,[{id:legacy,reference:'FP-SEED-'+legacy,name:'Существующий клиент'}]);assert.equal(db.prepare('SELECT COUNT(*) n FROM leads').get().n,1);
const created=crm.create({...manual,allowDuplicate:true},'manager');assert.equal(created.duplicate,false);assert.equal(created.leadRevision,1);assert.equal(created.leadStatus,'new');const stored=JSON.parse(db.prepare('SELECT payload FROM leads WHERE id=?').get(created.id).payload);assert.equal(stored.city,'Уточняется');assert.equal(stored.object,'Уточняется');assert.equal(stored.timing,'Уточняется');assert.deepEqual(stored.services,[]);assert.equal(stored.consentAt,undefined,'manager does not forge customer consent');assert.equal(db.prepare('SELECT COUNT(*) n FROM outbox').get().n,0,'manual creation sends no customer mail');
assert.equal(crm.create({...manual,allowDuplicate:true},'manager').duplicate,true,'idempotent retry precedes duplicate contact check');assert.throws(()=>crm.create({...manual,allowDuplicate:true,name:'Изменено'},'manager'),{status:409});
for(const bad of [{phone:'abc',email:''},{phone:'',email:''},{assignee:'missing'},{next_contact:'2026-02-30',next_action:'Call'},{next_contact:'2026-10-08',next_action:''},{services:['unknown']},{source:'social'},{projectLink:'http://example.com'},{allowDuplicate:'yes'},{idempotency:'not-uuid'}])assert.throws(()=>crm.create({...manual,phone:'+7 999 321 98 76',email:'new@example.com',idempotency:randomUUID(),...bad},'manager'),{status:422});
clock.stamp='2026-10-07T03:10:00.000Z';const event={type:'call',text:'Уточнили объём работ.',idempotency:randomUUID()},history=crm.appendHistory(created.id,event,'manager');assert.equal(history.leadRevision,2);assert.equal(history.entries[0].type,'call');assert.equal(history.entries[0].createdBy,'manager');assert.equal(crm.appendHistory(created.id,event,'manager').duplicate,true);assert.equal(crm.history(created.id).entries.length,2);assert.throws(()=>crm.appendHistory(created.id,{...event,text:'Changed'},'manager'),{status:409});assert.throws(()=>crm.appendHistory(created.id,{...event,type:'status'},'manager'),{status:422});
const firstCommercial=crm.saveCommercial(created.id,{revision:0,amount:'1234,05',lossReason:''},'manager');assert.equal(firstCommercial.amount,'1234.05');assert.equal(firstCommercial.revision,1);assert.equal(firstCommercial.leadRevision,3);assert.throws(()=>crm.saveCommercial(created.id,{revision:0,amount:'1234.05',lossReason:''},'manager'),{status:409});for(const amount of ['0','1e3','-1','1.001','10000000000','NaN'])assert.throws(()=>crm.saveCommercial(created.id,{revision:1,amount,lossReason:''},'manager'),{status:422});
const old=db.prepare('SELECT * FROM leads WHERE id=?').get(created.id),patch={status:'won',note:old.note,assignee:old.assignee,next_contact:old.next_contact,next_action:old.next_action};atomic(()=>{db.prepare("UPDATE leads SET status='won',revision=revision+1 WHERE id=?").run(created.id);crm.recordStatus(old,patch,'manager');});assert.equal(crm.history(created.id).entries[0].type,'status');assert.equal(crm.history(created.id).entries[0].fromStatus,'new');assert.equal(crm.history(created.id).entries[0].toStatus,'won');
crm.captureAttribution(created.id,{source:'overwrite',campaign:'fake'});assert.equal(db.prepare('SELECT source FROM lead_attribution WHERE lead_id=?').get(created.id).source,'manual:phone','first source is immutable');
const web=seed({name:'Заявка с сайта'});atomic(()=>crm.captureAttribution(web,{source:'yandex',medium:'cpc',campaign:'facade',content:'banner',term:'glass',landing:'/services/glazing.html?foo=bar#section',extra:'ignored'}));assert.equal(db.prepare('SELECT landing FROM lead_attribution WHERE lead_id=?').get(web).landing,'/services/glazing.html');assert.deepEqual(Object.keys(validateAttribution({source:'x',secret:'drop'})),['source','medium','campaign','content','term','landing']);for(const input of [null,[],{source:'x'.repeat(81)},{campaign:'\nsecret'},{landing:'https://example.com'},{landing:'//evil.test'},{landing:'/\\evil'}])assert.throws(()=>validateAttribution(input),{status:422});
db.prepare('INSERT INTO quote_versions VALUES(?,?)').run(randomUUID(),created.id);const closed=seed({name:'Закрытая заявка'},{status:'closed'});crm.saveCommercial(closed,{revision:0,amount:'',lossReason:'Сроки не подошли'},'manager');const oldWon=seed({}, {created:'2026-01-01T00:00:00.000Z',status:'won'});crm.saveCommercial(oldWon,{revision:0,amount:'10000',lossReason:''},'manager');const unknownWon=seed({}, {status:'won'});
const sales=crm.sales({days:7});assert.equal(sales.totals.leads,5);assert.equal(sales.totals.quoted,1);assert.equal(sales.totals.won,2);assert.equal(sales.totals.contractAmount,'1234.05');assert.equal(sales.totals.wonWithoutAmount,1);assert.equal(sales.totals.wonWithoutQuote,1);assert.equal(sales.firstAction.known,2);assert.equal(sales.firstAction.unknown,3);assert.equal(sales.firstAction.medianSeconds,43800);assert.deepEqual(sales.lossReasons,[{reason:'Сроки не подошли',count:1}]);assert.equal(sales.sources.find(s=>s.source==='manual:phone').contractAmount,'1234.05');assert.throws(()=>crm.sales({days:14}),{status:422});
// Every deal is valid on its own, but their exact combined kopecks exceed 2^53.
const maxAmount=999999999999n,highCount=10000;atomic(()=>{for(let i=0;i<highCount;i++){const id=seed({}, {status:'won'});db.prepare('INSERT INTO lead_commercial(lead_id,amount_kopecks,loss_reason,updated_at,updated_by) VALUES(?,?,?,?,?)').run(id,Number(maxAmount),'',clock.stamp,'manager');}});const high=crm.sales({days:7}),expected=123405n+maxAmount*BigInt(highCount),decimal=(expected/100n)+'.'+(expected%100n).toString().padStart(2,'0');assert.equal(high.totals.contractAmount,decimal);assert.equal(high.sources.find(s=>s.source==='Не указан').contractAmount,'99999999999900.00');
// Reinitialization leaves facts untouched; FK deletion removes only this lead's extensions.
createCRM15(options);assert.equal(crm.commercial(created.id).amount,'1234.05');db.prepare('DELETE FROM leads WHERE id=?').run(created.id);for(const table of ['lead_history','lead_commercial','lead_attribution'])assert.equal(db.prepare('SELECT COUNT(*) n FROM '+table+' WHERE lead_id=?').get(created.id).n,0);assert.throws(()=>crm.history(created.id),{status:404});assert.equal(db.prepare('SELECT COUNT(*) n FROM lead_history WHERE lead_id=?').get(closed).n,1);
db.close();console.log('PASS CRM15: preserved legacy records, normalized duplicate/override, idempotency, manual validation, no mail/consent fabrication, atomic history/revisions, commercial conflicts/precision, immutable attribution, lead cohorts/known first actions, exact high-value BigInt totals and FK cascade');
