import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {createQuoteTools16} from '../backend/quote-tools16.mjs';
import {createCRM15} from '../backend/crm15.mjs';

const db=new DatabaseSync(':memory:');
db.exec(`PRAGMA foreign_keys=ON;
 CREATE TABLE leads(id TEXT PRIMARY KEY,reference TEXT UNIQUE NOT NULL,created TEXT NOT NULL,kind TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'new',payload TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',revision INTEGER NOT NULL DEFAULT 1,idempotency TEXT UNIQUE NOT NULL,digest TEXT NOT NULL,session_id TEXT,assignee TEXT NOT NULL DEFAULT '',next_contact TEXT NOT NULL DEFAULT '',next_action TEXT NOT NULL DEFAULT '');
 CREATE TABLE quote_versions(id TEXT PRIMARY KEY,lead_id TEXT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,document_json TEXT NOT NULL);
 CREATE TABLE outbox(id TEXT PRIMARY KEY,lead_id TEXT REFERENCES leads(id) ON DELETE CASCADE);`);
const fail=(status,message)=>Object.assign(new Error(message),{status});
const atomic=fn=>{db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}};
const clock={stamp:'2026-10-07T05:00:00.000Z'},auditEvents=[],settings={db,fail,transaction:atomic,SERVICE_IDS:['glazing','windows','repair','engineering','supply','height'],now:()=>new Date(clock.stamp),audit:(...args)=>auditEvents.push(args)};
const crm=createCRM15({...settings,STATUSES:{new:'Новая',won:'Договор'}}),tools=createQuoteTools16({...settings,crm});
const seed=()=>{const id=randomUUID();db.prepare('INSERT INTO leads(id,reference,created,kind,payload,idempotency,digest) VALUES(?,?,?,?,?,?,?)').run(id,'FP-'+id,clock.stamp,'request',JSON.stringify({name:'Существующий заказчик',company:'Компания клиента',phone:'PRIVATE',comment:'customer only'}),randomUUID(),'digest');return id;};
const leadId=seed(),otherLead=seed(),publicBefore=db.prepare('SELECT payload,note,status FROM leads WHERE id=?').get(leadId);
const document={idempotency:randomUUID(),title:'Монтаж витражей',items:[{title:'Монтаж секций',unit:'м²',quantity:'2,5',unitPrice:'1000,10'}],tax:{mode:'extra',rate:'22'},timeframe:'После готовности фронта работ',validUntil:'2026-12-31',payment:'Аванс по согласованию',exclusions:'Подъёмная техника отдельно',customerNote:'Условия уточняются по проекту'};
assert.deepEqual(tools.templates(),{templates:[]},'there are no invented reusable prices or work rates');
assert.deepEqual(tools.costing(leadId),{revision:0,basis:'comparable',revenue:'',costs:[],totalCost:'0.00',plannedMargin:null,marginPercent:null,note:'',updatedAt:'',updatedBy:'',leadRevision:1,leadStatus:'new'},'migration invents no costs or revenue');
assert.equal(crm.history(leadId).entries.length,0);
const input={idempotency:randomUUID(),name:'Остекление',serviceIds:['windows','glazing','glazing'],document:{...document,company:{legalName:'NOT FOR REUSE'},customer:{name:'PRIVATE'},totals:{totalKopecks:999},items:[{...document.items[0],lineTotalKopecks:123}]}};
const created=tools.templateCreate(input,'manager'),template=created.template;
assert.equal(created.duplicate,false);assert.equal(template.revision,1);assert.deepEqual(template.serviceIds,['glazing','windows']);assert.equal(template.document.items[0].quantity,'2.5');assert.equal(template.document.items[0].unitPrice,'1000.10');assert.equal(template.document.validUntil,'');
assert.deepEqual(Object.keys(template.document),['title','items','tax','timeframe','validUntil','payment','exclusions','customerNote']);assert.deepEqual(Object.keys(template.document.items[0]),['title','unit','quantity','unitPrice']);
assert.equal(JSON.stringify(template).includes('PRIVATE'),false);assert.equal(JSON.stringify(template).includes('NOT FOR REUSE'),false);assert.equal(JSON.stringify(template).includes(document.idempotency),false);
assert.equal(tools.templateCreate(input,'manager').duplicate,true);assert.equal(tools.templates().templates.length,1);assert.throws(()=>tools.templateCreate({...input,name:'Изменено'},'manager'),{status:409});
assert.throws(()=>tools.templateCreate({...input,idempotency:randomUUID(),serviceIds:['unknown']},'manager'),{status:422});assert.throws(()=>tools.templateCreate({...input,idempotency:randomUUID(),document:{...document,costs:[{unitPrice:'PRIVATE'}]}},'manager'),{status:422});
const update={...input,idempotency:randomUUID(),revision:1,name:'Монтаж витражей',document:{...document,timeframe:'По согласованному графику'}};
const updated=tools.templateUpdate(template.id,update,'other');assert.equal(updated.template.revision,2);assert.equal(updated.template.updatedBy,'other');assert.equal(tools.templateUpdate(template.id,update,'other').duplicate,true);assert.throws(()=>tools.templateUpdate(template.id,{...update,idempotency:randomUUID()},'manager'),{status:409});
const removal={idempotency:randomUUID(),revision:2};assert.throws(()=>tools.templateDelete(template.id,{...removal,revision:1},'manager'),{status:409});assert.equal(tools.templateDelete(template.id,removal,'manager').removed,true);assert.equal(tools.templateDelete(template.id,removal,'manager').duplicate,true);assert.equal(tools.templates().templates.length,0);assert.throws(()=>tools.templateUpdate(template.id,{...update,idempotency:randomUUID(),revision:3},'manager'),{status:404});assert.equal(tools.templateCreate(input,'manager').duplicate,true,'a lost original response never recreates an archived template');assert.equal(tools.templates().templates.length,0);
assert.equal(db.prepare('SELECT revision FROM leads WHERE id=?').get(leadId).revision,1,'global templates do not mutate any customer lead');assert.equal(crm.history(leadId).entries.length,0);assert.equal(db.prepare('SELECT COUNT(*) count FROM outbox').get().count,0);

// Quote snapshots are immutable and internal costing never enters their JSON.
const quoteId=randomUUID(),quoteJSON=JSON.stringify({company:{legalName:'Facade.PRO'},customer:{name:'Existing'},...document});db.prepare('INSERT INTO quote_versions VALUES(?,?,?)').run(quoteId,leadId,quoteJSON);
const first={revision:0,basis:'comparable',revenue:'100.05',costs:[{category:'crew',title:'Бригада',quantity:'0.005',unitPrice:'1.00'},{category:'equipment',title:'Техника',quantity:'2.5',unitPrice:'10.02'},{category:'materials',title:'Расходные материалы',quantity:'1',unitPrice:'0.00'}],note:'Суммы указаны на одной основе по НДС'};
const saved=tools.saveCosting(leadId,first,'manager');assert.equal(saved.costs[0].lineTotal,'0.01','half a kopeck rounds upwards exactly');assert.equal(saved.costs[1].lineTotal,'25.05');assert.equal(saved.totalCost,'25.06');assert.equal(saved.plannedMargin,'74.99');assert.equal(saved.marginPercent,'74.95');assert.equal(saved.revision,1);assert.equal(saved.leadRevision,2);assert.equal(saved.leadStatus,'new');assert.equal(saved.updatedBy,'manager');assert.equal(crm.history(leadId).entries[0].type,'costing_saved');assert.equal(crm.history(leadId).entries[0].text,'Внутренний плановый расчёт обновлён.');
assert.throws(()=>tools.saveCosting(leadId,first,'other'),{status:409});assert.equal(tools.costing(leadId).note,first.note);assert.equal(crm.history(leadId).entries.length,1,'conflicts write no history');
assert.equal(db.prepare('SELECT document_json FROM quote_versions WHERE id=?').get(quoteId).document_json,quoteJSON);assert.deepEqual(db.prepare('SELECT payload,note,status FROM leads WHERE id=?').get(leadId),publicBefore);assert.equal(db.prepare('SELECT COUNT(*) count FROM outbox').get().count,0,'costing never schedules customer mail');assert.equal(tools.costing(otherLead).revision,0);
const negative=tools.saveCosting(leadId,{revision:1,basis:'comparable',revenue:'2',costs:[{category:'other',title:'Расход',quantity:'1',unitPrice:'5'}],note:''},'manager');assert.equal(negative.plannedMargin,'-3.00');assert.equal(negative.marginPercent,'-150.00');
const zero=tools.saveCosting(leadId,{revision:2,basis:'comparable',revenue:'0',costs:[{category:'transport',title:'Доставка',quantity:'1',unitPrice:'1'}],note:''},'manager');assert.equal(zero.plannedMargin,'-1.00');assert.equal(zero.marginPercent,null);
const unknown=tools.saveCosting(leadId,{revision:3,basis:'comparable',revenue:'',costs:[],note:''},'manager');assert.equal(unknown.totalCost,'0.00');assert.equal(unknown.plannedMargin,null);assert.equal(unknown.marginPercent,null);
for(const invalid of [{basis:'mixed'},{revision:-1},{revision:'4'},{revenue:'-1'},{revenue:4},{revenue:'1e3'},{revenue:'1.001'},{revenue:'10000000000'},{note:'x'.repeat(2001)},{costs:Array(51).fill(first.costs[0])},{costs:[{...first.costs[0],category:'tax'}]},{costs:[{...first.costs[0],quantity:'0'}]},{costs:[{...first.costs[0],quantity:'1000000.001'}]},{costs:[{...first.costs[0],unitPrice:'1.001'}]},{costs:[{...first.costs[0],quantity:'1000000',unitPrice:'9999999999.99'}]},{costs:[{...first.costs[0],title:''}]}])assert.throws(()=>tools.saveCosting(leadId,{...first,revision:4,...invalid},'manager'),{status:422});
assert.equal(tools.costing(leadId).revision,4);assert.equal(crm.history(leadId).entries.length,4);
// Decimal precision remains exact near the supported maximum.
const large=tools.saveCosting(otherLead,{revision:0,basis:'comparable',revenue:'9999999999.99',costs:[{category:'materials',title:'Поставка',quantity:'1',unitPrice:'9999999999.98'}],note:''},'manager');assert.equal(large.totalCost,'9999999999.98');assert.equal(large.plannedMargin,'0.01');assert.equal(large.marginPercent,'0.00');
const roundingLead=seed(),fractional=tools.saveCosting(roundingLead,{revision:0,basis:'comparable',revenue:'6.00',costs:[{category:'other',title:'Расход',quantity:'1',unitPrice:'5'}],note:''},'manager');assert.equal(fractional.marginPercent,'16.67');
const smallRevenue=seed(),hugeNegative=tools.saveCosting(smallRevenue,{revision:0,basis:'comparable',revenue:'0.01',costs:[{category:'other',title:'Расход',quantity:'1',unitPrice:'9999999999.99'}],note:''},'manager');assert.equal(hugeNegative.plannedMargin,'-9999999999.98');assert.equal(hugeNegative.marginPercent,'-99999999999800.00','large ratios remain exact without Number conversion');
// Failed hooks must roll back the cost, lead revision, history and audit write.
const rollbackLead=seed(),rollbackTools=createQuoteTools16({...settings,crm,audit:()=>{throw new Error('audit failure');}});assert.throws(()=>rollbackTools.saveCosting(rollbackLead,{...first,revision:0},'manager'),/audit failure/);assert.equal(tools.costing(rollbackLead).revision,0);assert.equal(db.prepare('SELECT revision FROM leads WHERE id=?').get(rollbackLead).revision,1);assert.equal(crm.history(rollbackLead).entries.length,0);
const rollbackKey=randomUUID();assert.throws(()=>rollbackTools.templateCreate({...input,idempotency:rollbackKey},'manager'),/audit failure/);assert.equal(db.prepare('SELECT COUNT(*) count FROM quote_template_receipts16 WHERE idempotency=?').get(rollbackKey).count,0);assert.equal(tools.templates().templates.length,0);
// Additive initialization preserves saved state; deleting a lead removes its
// internal calculation and quote only, never global reusable templates.
const recreated=createQuoteTools16({...settings,crm});assert.equal(recreated.costing(otherLead).plannedMargin,'0.01');const reusable=tools.templateCreate({...input,idempotency:randomUUID()},'manager').template;db.prepare('DELETE FROM leads WHERE id=?').run(leadId);assert.equal(db.prepare('SELECT COUNT(*) count FROM lead_costing16 WHERE lead_id=?').get(leadId).count,0);assert.equal(db.prepare('SELECT COUNT(*) count FROM quote_versions WHERE lead_id=?').get(leadId).count,0);assert.equal(tools.templates().templates[0].id,reusable.id);assert.equal(tools.costing(otherLead).revision,1);assert.throws(()=>tools.costing(leadId),{status:404});assert.throws(()=>tools.costing('invalid'),{status:404});
atomic(()=>{for(let i=1;i<200;i++)db.prepare('INSERT INTO quote_templates16(id,name,service_ids,document_json,created_at,created_by,updated_at,updated_by) VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),'Образец '+i,'[]',JSON.stringify(reusable.document),clock.stamp,'manager',clock.stamp,'manager');});assert.equal(tools.templates().templates.length,200);const limitKey=randomUUID();assert.throws(()=>tools.templateCreate({...input,idempotency:limitKey},'manager'),{status:422});assert.equal(db.prepare('SELECT COUNT(*) count FROM quote_template_receipts16 WHERE idempotency=?').get(limitKey).count,0,'active-template limit does not consume a retry key');
db.close();console.log('PASS quote tools16: unseeded reusable templates, sanitized snapshots, exact normalized prices, idempotent create/update/archive, optimistic conflicts, private BigInt costing/negative margin/unknown revenue, immutable external quotes, transactional history rollback, additive migration and FK cascade');
