import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm,stat} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import {randomUUID} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import {DatabaseSync} from 'node:sqlite';
import {verifyBackup,restoreBackup} from '../backend/backups.mjs';

const root=new URL('../',import.meta.url).pathname,temp=await mkdtemp(path.join(os.tmpdir(),'facadepro-server16-')),dataDir=path.join(temp,'data');
const listener=net.createServer();await new Promise(resolve=>listener.listen(0,'127.0.0.1',resolve));const port=listener.address().port;await new Promise(resolve=>listener.close(resolve));
const base='http://127.0.0.1:'+port,env={...process.env,DATA_DIR:dataDir,PORT:String(port),PUBLIC_URL:base,NODE_ENV:'test',SMTP_HOST:'',SMTP_FROM:'',SMTP_PASSWORD:'',LEAD_TO:'manager@example.test',TELEGRAM_BOT_TOKEN:'',TELEGRAM_CHAT_ID:'',BACKUP_ENABLED:'false'};
let server,log='';const sessions={};
function command(args){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,args,{cwd:root,env});let out='',err='';child.stdout.on('data',buffer=>out+=buffer);child.stderr.on('data',buffer=>err+=buffer);child.on('error',reject);child.on('close',code=>code?reject(Error(err||out)):resolve(out));});}
async function start(){log='';server=spawn(process.execPath,['server.mjs'],{cwd:root,env});server.stdout.on('data',buffer=>log+=buffer);server.stderr.on('data',buffer=>log+=buffer);for(let i=0;i<250;i++){if(server.exitCode!==null)throw Error(log);try{if((await fetch(base+'/healthz')).ok)return;}catch{}await delay(50);}throw Error('Server start: '+log);}
async function stop(){if(server&&server.exitCode===null&&server.signalCode===null)await new Promise(resolve=>{server.once('close',resolve);server.kill('SIGTERM');});server=null;}
async function call(route,{method='GET',body,auth=false,token,csrfToken,origin=base,form=false}={}){const headers={};if(!['GET','HEAD'].includes(method))headers.Origin=origin;if(auth){const session=sessions[auth===true?'server16':auth];headers.Cookie=session.cookie;if(!['GET','HEAD'].includes(method))headers['X-CSRF-Token']=csrfToken??session.csrf;}if(token)headers.Authorization='Bearer '+token;if(body!==undefined&&!form)headers['Content-Type']='application/json';return fetch(base+route,{method,headers,body:body!==undefined?(form?body:JSON.stringify(body)):undefined});}
async function json(route,options={},status=200){const response=await call(route,options);assert.equal(response.status,status,route+': '+await response.clone().text());return response.json();}
function database(fn){const db=new DatabaseSync(path.join(dataDir,'facadepro.sqlite'));try{db.exec('PRAGMA foreign_keys=ON');return fn(db);}finally{db.close();}}
async function login(username,password){const response=await call('/api/admin/login',{method:'POST',body:{username,password}});assert.equal(response.status,200);sessions[username]={cookie:response.headers.get('set-cookie').split(';')[0],csrf:(await response.json()).csrf};}
const document=()=>({idempotency:randomUUID(),title:'Предложение по фасаду',items:[{title:'Монтаж витража',unit:'м²',quantity:'2.5',unitPrice:'1000.10'}],tax:{mode:'extra',rate:'22'},timeframe:'20 рабочих дней',validUntil:'',payment:'Аванс по согласованию',exclusions:'Поставка металла',customerNote:'Уточним размеры'});
const manual=(assignee='server16')=>({name:'Заказчик для CRM16',phone:'+7 999 321 00 '+(assignee==='server16'?'11':'22'),email:assignee+'@example.test',company:'Строительная компания',source:'phone',services:['glazing'],assignee,idempotency:randomUUID(),allowDuplicate:false});
const requestForm=()=>{const form=new FormData();for(const [key,value] of Object.entries({kind:'quote',service:'glazing',name:'Заказчик КП16',company:'Клиентская компания',phone:'+7 999 111-22-33',city:'Владивосток',object:'Объект для КП16',timing:'Согласовать',consent:'yes',scope:'installation',idempotency:randomUUID(),sourcePage:'/for-contractors.html'}))form.set(key,value);return form;};
try{
 const passwords={};for(const username of ['server16','other16'])passwords[username]=(await command(['scripts/create-admin.mjs',username])).match(/Одноразовая выдача пароля: (.+)/)[1];await start();await login('server16',passwords.server16);await login('other16',passwords.other16);
 for(const route of ['/api/admin/day','/api/admin/incoming','/api/admin/quote-templates'])assert.equal((await call(route)).status,401,route+' requires staff session');
 const localDay=await json('/api/admin/day',{auth:true}),today=localDay.today,yesterday=new Date(Date.parse(today+'T00:00:00Z')-86400000).toISOString().slice(0,10);assert.equal(localDay.timezone,'Asia/Vladivostok');assert.deepEqual(localDay.counts,{overdue:0,today:0,new:0,incoming:0});
 const primary=await json('/api/admin/leads',{method:'POST',auth:true,body:{...manual(),next_contact:today,next_action:'Связаться сегодня'}},201),secondary=await json('/api/admin/leads',{method:'POST',auth:true,body:{...manual('other16'),next_contact:yesterday,next_action:'Просроченный контакт'}},201),manualRoute='/api/admin/leads/'+primary.id;
 let day=await json('/api/admin/day',{auth:true});assert.equal(day.counts.today,1);assert.equal(day.counts.overdue,0);assert.equal(day.counts.new,1);assert.equal(day.groups.today[0].id,primary.id);assert.equal(day.groups.today[0].payload.name,'Заказчик для CRM16');assert.equal(day.groups.today[0].payload.comment,undefined);day=await json('/api/admin/day',{auth:'other16'});assert.equal(day.counts.overdue,1);assert.equal(day.groups.overdue[0].id,secondary.id);
 const firstCall={idempotency:randomUUID(),revision:primary.leadRevision,outcome:'no_answer',comment:'Не дозвонились <script>literal</script>',next_contact:today,next_action:'Повторить звонок'};
 assert.equal((await call(manualRoute+'/call-result',{method:'POST',body:firstCall})).status,401);assert.equal((await call(manualRoute+'/call-result',{method:'POST',auth:true,csrfToken:'invalid',body:firstCall})).status,403);assert.equal((await call(manualRoute+'/call-result',{method:'POST',auth:true,body:firstCall,origin:'https://foreign.example'})).status,403);
 const concurrentCalls=await Promise.all([json(manualRoute+'/call-result',{method:'POST',auth:true,body:firstCall}),json(manualRoute+'/call-result',{method:'POST',auth:true,body:firstCall})]);assert.deepEqual(concurrentCalls.map(result=>result.duplicate).sort(),[false,true]);assert.equal(concurrentCalls[0].leadRevision,2);let detail=await json(manualRoute,{auth:true});assert.equal(detail.status,'new');assert.equal(detail.next_action,'Повторить звонок');assert.equal(detail.revision,2);let history=await json(manualRoute+'/history',{auth:true});assert.equal(history.entries.filter(entry=>entry.type==='call').length,1);assert.ok(history.entries.some(entry=>entry.text.includes('<script>literal</script>')));
 assert.equal((await call(manualRoute+'/call-result',{method:'POST',auth:true,body:{...firstCall,idempotency:randomUUID()}})).status,409);assert.equal((await call(manualRoute+'/call-result',{method:'POST',auth:true,body:{...firstCall,comment:'Changed'}})).status,409);
 await json(manualRoute,{method:'PATCH',auth:'other16',body:{status:'review',note:'Другой сотрудник сохранил заметку',revision:detail.revision,next_contact:today,next_action:'Встреча другого менеджера'}});const repeatedCall=await json(manualRoute+'/call-result',{method:'POST',auth:true,body:firstCall});assert.equal(repeatedCall.duplicate,true);assert.equal(repeatedCall.leadStatus,'review');assert.equal(repeatedCall.next_action,'Встреча другого менеджера');assert.equal(repeatedCall.entry.next_action,'Повторить звонок');assert.equal((await json(manualRoute,{auth:true})).note,'Другой сотрудник сохранил заметку');

 const request=await json('/api/requests',{method:'POST',form:true,body:requestForm()},201),token=request.continuationUrl.split('#')[1],leadList=await json('/api/admin/leads',{auth:true}),lead=leadList.rows.find(row=>row.reference===request.reference),route='/api/admin/leads/'+lead.id;
 detail=await json(route,{auth:true});await json(route,{method:'PATCH',auth:true,body:{status:detail.status,note:'STAFF_PRIVATE16',revision:detail.revision,assignee:'server16'}});
 const input=document(),built=await json(route+'/quotes/build',{method:'POST',auth:true,body:input},201),quoteFile=await call(built.quote.downloadUrl,{auth:true}),pdfBefore=Buffer.from(await quoteFile.arrayBuffer());assert.equal(pdfBefore.subarray(0,5).toString(),'%PDF-');
 const responsePath='/api/client/lead/quotes/'+built.quote.id+'/response',responseInput={idempotency:randomUUID(),choice:'reprice',comment:'Просим пересчитать объём <literal>'};assert.equal((await call(responsePath,{method:'POST',token,body:responseInput})).status,404,'unpublished PDF cannot receive a new customer response');
 let portal=await json(route+'/portal',{auth:true});portal=await json(route+'/portal',{method:'POST',auth:true,body:{action:'publishQuote',quoteId:built.quote.id,revision:portal.revision}});
 assert.equal((await call(responsePath,{method:'POST',body:responseInput})).status,404);assert.equal((await call(responsePath,{method:'POST',token,body:responseInput,origin:'https://foreign.example'})).status,403);assert.equal((await call(responsePath,{method:'POST',token,body:{...responseInput,choice:'won'}})).status,422);assert.equal((await call(responsePath,{method:'POST',token,body:{...responseInput,quoteId:randomUUID()}})).status,422);
 const responses=await Promise.all([json(responsePath,{method:'POST',token,body:responseInput}),json(responsePath,{method:'POST',token,body:responseInput})]);assert.deepEqual(responses.map(result=>result.replayed).sort(),[false,true]);assert.equal(responses[0].response.id,responses[1].response.id);assert.equal((await json('/api/client/lead',{token})).quote.response.choice,'reprice');assert.equal((await call(responsePath,{method:'POST',token,body:{...responseInput,comment:'Changed'}})).status,409);
 let incoming=await json('/api/admin/incoming?leadId='+lead.id,{auth:true});assert.equal(incoming.total,1);assert.equal(incoming.unread,1);assert.equal(incoming.entries[0].kind,'quote_response');assert.equal(incoming.entries[0].quoteVersion,1);assert.equal(incoming.entries[0].choice,'reprice');assert.equal(incoming.entries[0].comment,responseInput.comment);assert.equal(incoming.entries[0].revision,0);database(db=>{assert.equal(db.prepare("SELECT COUNT(*) n FROM outbox WHERE lead_id=? AND kind='quote_response'").get(lead.id).n,1,'retry enqueues one manager email');assert.equal(db.prepare('SELECT COUNT(*) n FROM lead_quote_responses16 WHERE lead_id=?').get(lead.id).n,1);});
 const incomingId=incoming.entries[0].id,revisionBeforeAck=(await json(route,{auth:true})).revision;assert.equal((await call('/api/admin/incoming/'+incomingId,{method:'PUT',body:{revision:0,processed:true}})).status,401);assert.equal((await call('/api/admin/incoming/'+incomingId,{method:'PUT',auth:true,csrfToken:'bad',body:{revision:0,processed:true}})).status,403);
 const ack=await json('/api/admin/incoming/'+incomingId,{method:'PUT',auth:true,body:{revision:0,processed:true}});assert.equal(ack.entry.processed,true);assert.equal(ack.entry.processedBy,'server16');assert.equal(ack.entry.revision,1);assert.equal((await json(route,{auth:true})).revision,revisionBeforeAck);assert.equal((await json(route,{auth:true})).unreadCount,0);assert.equal((await json(route,{auth:'other16'})).unreadCount,1);assert.equal((await json('/api/admin/incoming?leadId='+lead.id,{auth:'other16'})).unread,1);assert.equal((await call('/api/admin/incoming/'+incomingId,{method:'PUT',auth:true,body:{revision:0,processed:false}})).status,409);assert.equal((await json('/api/admin/incoming/'+incomingId,{method:'PUT',auth:true,body:{revision:1,processed:true}})).entry.revision,1);
 assert.equal((await json('/api/admin/leads?incoming=1',{auth:true})).total,0);assert.equal((await json('/api/admin/leads?incoming=1',{auth:'other16'})).total,1);assert.equal((await json('/api/admin/day',{auth:true})).counts.incoming,0);
 const appendInput=()=>{const form=new FormData();form.set('idempotency',additionKey);form.set('comment','Новый проект');form.set('projectLink','https://example.com/project16');form.append('files',new Blob(['Материалы для проекта16'],{type:'text/plain'}),'project16.txt');return form;},additionKey=randomUUID();await json('/api/client/lead/append',{method:'POST',token,form:true,body:appendInput()});await json('/api/client/lead/append',{method:'POST',token,form:true,body:appendInput()});incoming=await json('/api/admin/incoming?mine=1&leadId='+lead.id,{auth:true});assert.equal(incoming.total,2);assert.equal(incoming.unread,1);assert.equal(incoming.entries[0].kind,'addition');assert.equal(incoming.entries[0].filesCount,1);assert.equal((await json('/api/admin/day',{auth:true})).counts.incoming,1);assert.equal((await json('/api/admin/leads?incoming=1',{auth:true})).rows[0].unreadCount,1);database(db=>{assert.equal(db.prepare("SELECT COUNT(*) n FROM outbox WHERE lead_id=? AND kind='addition'").get(lead.id).n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM lead_additions WHERE lead_id=?').get(lead.id).n,1);});
 const proceed=await json(responsePath,{method:'POST',token,body:{idempotency:randomUUID(),choice:'proceed',comment:'Готов перейти к договору'}});assert.equal(proceed.replayed,false);detail=await json(route,{auth:true});assert.equal(detail.status,'sent','customer intent does not infer a signed contract');assert.equal(detail.commercial.amount,'');assert.equal((await json('/api/admin/sales?days=30',{auth:true})).totals.won,0);assert.equal((await json('/api/admin/incoming?leadId='+lead.id,{auth:true})).unread,2);history=await json(route+'/history',{auth:true});assert.equal(history.entries.some(entry=>entry.type==='call'&&entry.text.includes('Готов перейти')),false,'customer response is not a forged manager activity');

 assert.equal((await json('/api/admin/quote-templates',{auth:true})).templates.length,0,'no invented company defaults');const templateInput={idempotency:randomUUID(),name:'Остекление — базовый состав',serviceIds:['glazing'],document:{...built.quote.document,customer:{name:'DROP_CUSTOMER16'},company:{legalName:'DROP_COMPANY16'},validUntil:'2026-12-31'}};
 assert.equal((await call('/api/admin/quote-templates',{method:'POST',auth:true,csrfToken:'bad',body:templateInput})).status,403);const template=await json('/api/admin/quote-templates',{method:'POST',auth:true,body:templateInput},201);assert.equal(template.template.document.customer,undefined);assert.equal(template.template.document.company,undefined);assert.equal(template.template.document.totals,undefined);assert.equal(template.template.document.validUntil,'');assert.equal((await json('/api/admin/quote-templates',{method:'POST',auth:true,body:templateInput})).template.id,template.template.id);assert.equal((await call('/api/admin/quote-templates',{method:'POST',auth:true,body:{...templateInput,name:'Changed'}})).status,409);
 const templateRoute='/api/admin/quote-templates/'+template.template.id,update={...templateInput,idempotency:randomUUID(),revision:1,name:'Остекление — обновлённые условия'};const updated=await json(templateRoute,{method:'PUT',auth:true,body:update});assert.equal(updated.template.revision,2);assert.equal((await json(templateRoute,{method:'PUT',auth:true,body:update})).duplicate,true);assert.equal((await call(templateRoute,{method:'PUT',auth:'other16',body:{...update,idempotency:randomUUID(),name:'Foreign stale write'}})).status,409);
 const archiveInput={revision:2,idempotency:randomUUID()};await json(templateRoute,{method:'DELETE',auth:true,body:archiveInput});assert.equal((await json(templateRoute,{method:'DELETE',auth:true,body:archiveInput})).duplicate,true);assert.equal((await json('/api/admin/quote-templates',{auth:true})).templates.length,0);const reusable=await json('/api/admin/quote-templates',{method:'POST',auth:true,body:{...templateInput,idempotency:randomUUID(),name:'Постоянный шаблон'}},201);
 assert.equal((await call(route+'/costing')).status,401);assert.equal((await call(route+'/costing',{token})).status,401);let costing=await json(route+'/costing',{auth:true});assert.equal(costing.revision,0);assert.equal(costing.plannedMargin,null);const costingInput={revision:0,basis:'comparable',revenue:'2000.10',costs:[{category:'crew',title:'Бригада COST_PRIVATE16',quantity:'1.5',unitPrice:'1000.10'},{category:'materials',title:'Материалы',quantity:'2',unitPrice:'600.20'}],note:'INTERNAL_MARGIN_PRIVATE16'};
 assert.equal((await call(route+'/costing',{method:'PUT',auth:true,csrfToken:'bad',body:costingInput})).status,403);costing=await json(route+'/costing',{method:'PUT',auth:true,body:costingInput});assert.equal(costing.totalCost,'2700.55');assert.equal(costing.plannedMargin,'-700.45');assert.equal(costing.marginPercent,'-35.02');assert.equal(costing.costs[0].lineTotal,'1500.15');assert.equal(costing.leadStatus,'sent');assert.equal((await call(route+'/costing',{method:'PUT',auth:'other16',body:{...costingInput,revenue:'5000'}})).status,409);
 const clientAfterCost=JSON.stringify(await json('/api/client/lead',{token}));for(const marker of ['COST_PRIVATE16','INTERNAL_MARGIN_PRIVATE16','STAFF_PRIVATE16','plannedMargin','totalCost','costing','DROP_CUSTOMER16','DROP_COMPANY16'])assert.equal(clientAfterCost.includes(marker),false,'customer projection excludes '+marker);const pdfAfter=Buffer.from(await (await call('/api/client/lead/quotes/'+built.quote.id+'/file',{token})).arrayBuffer());assert.equal(pdfBefore.equals(pdfAfter),true,'private economics cannot alter the customer PDF');const publicPage=await (await call('/')).text();assert.equal(publicPage.includes('INTERNAL_MARGIN_PRIVATE16'),false);
 const beforeUnset=costing.revision;costing=await json(route+'/costing',{method:'PUT',auth:true,body:{...costingInput,revision:beforeUnset,revenue:''}});assert.equal(costing.plannedMargin,null);assert.equal(costing.marginPercent,null);assert.equal(costing.totalCost,'2700.55');assert.equal((await json(route,{auth:true})).commercial.amount,'','economics never changes the recorded contract sum');
 const secondQuote=await json(route+'/quotes/build',{method:'POST',auth:true,body:{...document(),items:[{title:'Новый объём',unit:'м²',quantity:'3',unitPrice:'1000.10'}]}},201);portal=await json(route+'/portal',{auth:true});await json(route+'/portal',{method:'POST',auth:true,body:{action:'publishQuote',quoteId:secondQuote.quote.id,revision:portal.revision}});const oldReplay=await json(responsePath,{method:'POST',token,body:responseInput});assert.equal(oldReplay.replayed,true);assert.equal(oldReplay.response.quoteId,built.quote.id);assert.equal(oldReplay.lead.quote.id,secondQuote.quote.id);assert.equal(oldReplay.lead.quote.response,null);assert.equal((await call(responsePath,{method:'POST',token,body:{...responseInput,idempotency:randomUUID()}})).status,404);
 portal=await json(route+'/portal',{auth:true});const rotated=await json(route+'/portal',{method:'POST',auth:true,body:{action:'issue',revision:portal.revision}}),newToken=rotated.url.split('#')[1];assert.equal((await call(responsePath,{method:'POST',token,body:responseInput})).status,404,'rotated token cannot replay private receipts');assert.equal((await json('/api/client/lead',{token:newToken})).quote.id,secondQuote.quote.id);

 // Persist enough independent fixture events to prove the unread predicate is
 // applied before count and pagination, rather than filtering a 50-row page.
 const bulkIds=database(db=>{const ids=[];db.exec('BEGIN IMMEDIATE');try{for(let i=0;i<51;i++){const id=randomUUID(),eventId=randomUUID();ids.push(id);db.prepare('INSERT INTO leads(id,reference,created,kind,status,payload,idempotency,digest,assignee) VALUES(?,?,?,?,?,?,?,?,?)').run(id,'FP-BULK16-'+String(i).padStart(2,'0'),new Date().toISOString(),'manual','new',JSON.stringify({name:'Очередь '+i,phone:'',email:''}),randomUUID(),'bulk-fixture','server16');db.prepare("INSERT INTO lead_incoming16(id,lead_id,kind,event_id,created_at,comment,project_link,files_count) VALUES(?,?,'addition',?,?,?,'',0)").run(randomUUID(),id,eventId,new Date().toISOString(),'Входящее '+i);}db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return ids;});
 const firstPage=await json('/api/admin/leads?incoming=1',{auth:true}),secondPage=await json('/api/admin/leads?incoming=1&offset=50',{auth:true});assert.equal(firstPage.total,52);assert.equal(firstPage.rows.length,50);assert.equal(secondPage.rows.length,2);assert.equal(secondPage.total,52);assert.equal(new Set([...firstPage.rows,...secondPage.rows].map(row=>row.id)).size,52);assert.equal((await json('/api/admin/leads?incoming=1&assignee=@me',{auth:true})).total,52);assert.equal((await json('/api/admin/leads?incoming=1&assignee=@me',{auth:'other16'})).total,0);assert.equal((await json('/api/admin/incoming?limit=2&offset=1',{auth:true})).hasMore,true);assert.equal((await call('/api/admin/incoming?limit=101',{auth:true})).status,422);
 const files=database(db=>db.prepare('SELECT file_key FROM quote_versions WHERE lead_id=?').all(lead.id).concat(db.prepare("SELECT 'uploads/'||id file_key FROM files WHERE lead_id=?").all(lead.id)));await stop();const backup=JSON.parse((await command(['scripts/backup-data.mjs'])).trim()),directory=path.join(dataDir,'backups',backup.backup);assert.equal((await verifyBackup(directory)).verified,true);const restoredPath=path.join(temp,'restored');await restoreBackup(directory,restoredPath);const restored=new DatabaseSync(path.join(restoredPath,'facadepro.sqlite'),{readOnly:true});try{assert.equal(restored.prepare('SELECT COUNT(*) n FROM lead_calls16').get().n,1);assert.equal(restored.prepare('SELECT COUNT(*) n FROM lead_quote_responses16 WHERE lead_id=?').get(lead.id).n,2);assert.equal(restored.prepare('SELECT COUNT(*) n FROM lead_incoming16 WHERE lead_id=?').get(lead.id).n,3);assert.equal(restored.prepare('SELECT processed FROM lead_incoming_ack16 WHERE incoming_id=? AND username=?').get(incomingId,'server16').processed,1);assert.equal(restored.prepare('SELECT note FROM lead_costing16 WHERE lead_id=?').get(lead.id).note,'INTERNAL_MARGIN_PRIVATE16');assert.equal(restored.prepare('SELECT archived FROM quote_templates16 WHERE id=?').get(reusable.template.id).archived,0);}finally{restored.close();}
 await start();assert.equal((await json('/api/client/lead',{token:newToken})).quote.id,secondQuote.quote.id);assert.equal((await json('/api/admin/incoming?leadId='+lead.id,{auth:true})).unread,2);assert.equal((await json('/api/admin/incoming?leadId='+lead.id,{auth:'other16'})).unread,3);assert.equal((await json(route+'/costing',{auth:true})).totalCost,'2700.55');assert.equal((await json(manualRoute+'/call-result',{method:'POST',auth:true,body:firstCall})).duplicate,true);
 await json(route,{method:'DELETE',auth:true});assert.equal((await call('/api/client/lead',{token:newToken})).status,404);for(const file of files)await assert.rejects(()=>stat(path.join(dataDir,file.file_key)),{code:'ENOENT'});database(db=>{for(const table of ['lead_incoming16','lead_quote_responses16','lead_costing16'])assert.equal(db.prepare('SELECT COUNT(*) n FROM '+table+' WHERE lead_id=?').get(lead.id).n,0);assert.equal(db.prepare('SELECT COUNT(*) n FROM lead_incoming_ack16 WHERE incoming_id=?').get(incomingId).n,0);});assert.equal((await json('/api/admin/quote-templates',{auth:true})).templates[0].id,reusable.template.id);assert.equal((await json('/api/admin/leads?incoming=1',{auth:true})).total,bulkIds.length);
 await json(manualRoute,{method:'DELETE',auth:true});database(db=>assert.equal(db.prepare('SELECT COUNT(*) n FROM lead_calls16 WHERE lead_id=?').get(primary.id).n,0));
 console.log('PASS v16 HTTP: staff/CSRF/origin protection, assigned local day, atomic concurrent calls and stale/replay conflicts, personal incoming acknowledgments/counts/pagination, published customer replies and genuine outbox dedupe, no automatic contract/status, sanitized reusable templates, exact private negative/unknown economics, unchanged public PDF, rotated receipt access, restart/backup/restore and deletion cascades');
}catch(error){console.error(error);console.error(log.slice(-2000));process.exitCode=1;}finally{await stop();await rm(temp,{recursive:true,force:true});}
